#pragma once

#include <prim/seadSafeString.h>

namespace al {
class ActorInitInfo;
class LiveActor;
class Scene;
class IUseSceneObjHolder;
}  // namespace al
class BarrierField;
class OceanWaveActor;
class ShineTowerRocket;
class RiseMapPartsHolder;
class Shine;
class IUseDemoSkip;
class CaptionInfoHolder;
class CinemaCaption;

namespace rs {
al::LiveActor* createDemoPeachWedding(const al::ActorInitInfo&);
al::LiveActor* createDemoCapManHeroine(const al::ActorInitInfo&);
bool isRandomActionDemoChangeWorld(const al::LiveActor*, const char*);
bool tryGetDemoChangeWorldRandomActionName(sead::BufferedSafeString*, s32*, const al::LiveActor*,
                                           const char*);

bool requestStartDemoNormal(al::LiveActor*, bool);
void addDemoActor(al::LiveActor*, bool);
bool requestEndDemoNormal(const al::LiveActor*);
bool requestStartDemoNormal(const al::Scene*);
bool requestEndDemoNormal(const al::Scene*);
bool requestStartDemoNormalWithCinemaFrame(al::LiveActor*);
bool requestEndDemoNormalWithCinemaFrame(const al::LiveActor*);
bool requestStartDemoWithPlayer(al::LiveActor*, bool);
bool requestEndDemoWithPlayer(const al::LiveActor*);
bool requestStartDemoWithPlayer(const al::Scene*);
bool requestEndDemoWithPlayer(const al::Scene*);
bool requestStartDemoWithPlayerCinemaFrame(al::LiveActor*, bool);
bool requestEndDemoWithPlayerCinemaFrame(const al::LiveActor*);
bool requestStartDemoWithPlayerKeepCarry(al::LiveActor*, bool);
bool requestEndDemoWithPlayerKeepCarry(const al::LiveActor*);
bool requestStartDemoWithPlayerUseCoin(al::LiveActor*, bool);
bool requestEndDemoWithPlayerUseCoin(const al::LiveActor*);
bool requestStartDemoWithPlayerKeepBindTalk(al::LiveActor*, bool);
bool requestEndDemoWithPlayerKeepBindTalk(const al::LiveActor*);
bool requestStartDemoKeepHackTalk(al::LiveActor*, bool);
bool requestEndDemoKeepHackTalk(const al::LiveActor*);
bool requestStartDemoWithPlayerCinemaFrameTalk(al::LiveActor*, bool);
bool requestEndDemoWithPlayerCinemaFrameTalk(const al::LiveActor*);
bool requestStartDemoWithPlayerKeepCarryTalk(al::LiveActor*, bool);
bool requestEndDemoWithPlayerKeepCarryTalk(const al::LiveActor*);
bool requestStartDemoWithPlayerUseCoinTalk(al::LiveActor*, bool);
bool requestEndDemoWithPlayerUseCoinTalk(const al::LiveActor*);
bool requestStartDemoNormalTalk(al::LiveActor*, bool);
bool requestEndDemoNormalTalk(const al::LiveActor*);
bool requestStartDemoWarpToCheckpoint(const al::Scene*);
bool requestStartDemoBossBattleStart(al::LiveActor*);
bool requestEndDemoBossBattleStart(const al::LiveActor*);
bool requestStartDemoBossBattleEnd(al::LiveActor*);
bool requestEndDemoBossBattleEnd(const al::LiveActor*);
bool requestStartDemoShineGet(Shine*);
bool requestStartDemoAchievementShineGet(al::Scene*);
void endDemoShineGet(al::Scene*);
bool requestEndDemoShineGet(const al::Scene*);
bool requestEndDemoShineGet(const al::LiveActor*);
bool requestStartDemoShineDotGet(Shine*);
bool requestEndDemoShineDotGet(const al::Scene*);
bool requestStartDemoShineMainGet(Shine*);
void setDemoInfoDemoName(const al::LiveActor*, const char*);
bool requestEndDemoShineMainGet(const al::LiveActor*);
bool requestEndDemoShineMainGet(const al::Scene*);
bool requestStartDemoShineGrandGet(Shine*);
bool requestEndDemoShineGrandGet(const al::LiveActor*);
bool requestEndDemoShineGrandGet(const al::Scene*);
bool requestStartDemoShineAppear(al::LiveActor*);
bool requestEndDemoShineAppear(const al::LiveActor*);
bool requestStartDemoShineAppear(const al::Scene*);
bool requestEndDemoShineAppear(const al::Scene*);
bool requestStartDemoWarp(al::LiveActor*);
bool requestStartDemoWarp(const al::Scene*);
bool requestEndDemoWarp(const al::LiveActor*);
bool requestEndDemoWarp(const al::Scene*);
bool requestStartDemoHackStart(al::LiveActor*);
bool requestEndDemoHackStart(const al::LiveActor*);
bool requestStartDemoAppearByBazookaElectric(al::LiveActor*);
bool requestEndDemoAppearByBazookaElectric(const al::LiveActor*);
bool requestStartDemoLaunchBazookaElectric(al::LiveActor*);
bool requestEndDemoLaunchBazookaElectric(const al::LiveActor*);
bool requestStartDemoSceneStartPlayerWalk(al::LiveActor*);
bool requestEndDemoSceneStartPlayerWalk(const al::LiveActor*);
bool requestStartDemoGetLifeMaxUpItem(al::LiveActor*);
bool requestEndDemoGetLifeMaxUpItem(const al::Scene*);
bool requestStartDemoBirdCarryMeat(al::LiveActor*);
bool requestEndDemoBirdCarryMeat(const al::LiveActor*);
bool requestStartDemoBirdFindMeat(al::LiveActor*);
bool requestEndDemoBirdFindMeat(const al::LiveActor*);
bool requestStartDemoGetTimeBalloon(al::LiveActor*);
bool requestEndDemoGetTimeBalloon(const al::LiveActor*);
bool requestStartDemoJango(al::LiveActor*);
bool requestEndDemoJango(const al::LiveActor*);
bool requestStartDemoTitleLogo(const al::LiveActor*);
bool requestStartDemoGoToEnding(al::LiveActor*);

bool isActiveDemo(const al::LiveActor*);
bool isActiveDemo(const al::Scene*);
bool isActiveDemoNormal(const al::Scene*);
bool isActiveDemoNormalWithCinemaFrame(const al::Scene*);
bool isActiveDemoWithPlayer(const al::Scene*);
bool isActiveDemoWithPlayer(const al::LiveActor*);
bool isActiveDemoWithPlayerCinemaFrame(const al::Scene*);
bool isActiveDemoWithPlayerCinemaFrame(const al::LiveActor*);
bool isActiveDemoWithPlayerKeepCarry(const al::Scene*);
bool isActiveDemoWithPlayerKeepCarry(const al::LiveActor*);
bool isActiveDemoWithPlayerUseCoin(const al::Scene*);
bool isActiveDemoWithPlayerUseCoin(const al::LiveActor*);
bool isActiveDemoWithPlayerKeepBindTalk(const al::Scene*);
bool isActiveDemoWithPlayerKeepBindTalk(const al::LiveActor*);
bool isActiveDemoWarpToCheckpoint(const al::LiveActor*);
bool isActiveDemoShineGet(const al::Scene*);
bool isActiveDemoShineGet(const al::LiveActor*);
bool isActiveDemoShineDotGet(const al::Scene*);
bool isActiveDemoShineDotGet(const al::LiveActor*);
bool isActiveDemoShineGrandGet(const al::Scene*);
bool isActiveDemoShineGrandGet(const al::LiveActor*);
bool isActiveDemoShineMainGet(const al::Scene*);
bool isActiveDemoShineMainGet(const al::LiveActor*);
bool isActiveDemoWarp(const al::Scene*);
bool isActiveDemoWarp(const al::LiveActor*);
bool isActiveDemoHackStart(const al::LiveActor*);
bool isActiveDemoHackStart(const al::Scene*);
bool isActiveDemoHackStartFirst(const al::Scene*);
bool isEqualDemoInfoDemoName(const al::Scene*, const char*);
bool isActiveDemoScenarioCamera(const al::LiveActor*);
bool isActiveDemoGetLifeMaxUpItem(const al::Scene*);
bool isActiveDemoSceneStartPlayerWalk(const al::Scene*);
bool isActiveDemoBirdCarryMeat(const al::Scene*);
bool isActiveDemoBirdFindMeat(const al::Scene*);
bool isActiveDemoJango(const al::Scene*);
bool isActiveDemoJango(const al::LiveActor*);
bool isActiveDemoTitleLogo(const al::Scene*);
bool isActiveDemoGoToEnding(const al::Scene*);
bool isActiveDemoTalk(const al::Scene*);
bool isActiveDemoCinemaFrameTalk(const al::Scene*);
bool isActiveDemoKeepCarryTalk(const al::Scene*);
bool isActiveDemoUseCoinTalk(const al::Scene*);
bool isActiveDemoKeepHackTalk(const al::Scene*);
bool isActiveDemoNormalTalk(const al::Scene*);
bool isActiveDemoLaunchBazookaElectric(const al::Scene*);
bool isActiveDemoGiantWanderBossBattleStart(const al::Scene*);
bool isActiveDemoGiantWanderBossBattleStart(const OceanWaveActor*);
bool isActiveDemoPlayerPuppetable(const al::LiveActor*);

void addDemoSubActor(al::LiveActor*);
void registerShineTowerRocketToDemoDirector(ShineTowerRocket*);
void tryGetShineTowerRocketFromDemoDirector(al::LiveActor*);
void addDemoAppearFromHomeToList(ShineTowerRocket*);
void addDemoReturnToHomeToList(ShineTowerRocket*);
void addDemoRiseMapPartsToList(RiseMapPartsHolder*);

bool requestStartDemoWorldIntroCamera(const al::Scene*);
bool requestEndDemoWorldIntroCamera(const al::Scene*);
bool requestStartDemoScenarioCamera(const al::Scene*);
bool requestEndDemoScenarioCamera(const al::LiveActor*);
bool requestStartDemoAppearFromHome(const al::Scene*);
bool requestEndDemoAppearFromHome(const al::LiveActor*);
bool requestStartDemoReturnToHome(const al::Scene*);
bool requestEndDemoReturnToHome(const al::LiveActor*);
bool requestStartDemoRiseMapParts(const al::Scene*);
bool requestEndDemoRiseMapParts(const al::LiveActor*);
bool requestStartDemoPeachCastleCap(al::LiveActor*);
bool requestEndDemoPeachCastleCap(const al::LiveActor*);

bool isExistDemoAppearFromHomeInList(const al::Scene*);
bool isExistDemoReturnToHome(const al::Scene*);
bool isExistDemoRiseMapPartsInList(const al::Scene*);

al::LiveActor* getRequestActor(const al::Scene*);
void requestValidateDemoSkip(IUseDemoSkip*, const al::LiveActor*);
void* getDemoSkipRequester(const al::Scene*);
bool isDemoEnableSkip(const al::Scene*);
bool isFirstDemo(const al::Scene*);
bool isEnableSkipDemo(const al::Scene*);
void skipDemo(const al::Scene*);
void updateOnlyDemoGraphics(const al::Scene*);
bool isFirstDemoWorldIntroCamera(const al::Scene*);
bool isFirstDemoScenarioStartCamera(const al::LiveActor*);
void noticeDemoSkipStart(const al::Scene*);
void noticeDemoSkipEnd(const al::Scene*);
bool isWaitDemoSkipEnd(const al::LiveActor*);
CaptionInfoHolder* createCaptionInfoHolder(const char*);
void validateDemoCaption(const al::LiveActor*, CaptionInfoHolder*);
bool isActiveDemoWithCinemaCaption(const al::Scene*);
void tryAppearCinemaCaption(const al::Scene*, CinemaCaption*);
void startCloseDemoFade(const al::LiveActor*, s32);
void startOpenDemoFade(const al::LiveActor*, s32);
bool isDemoFadeCloseEnd(const al::LiveActor*);
bool isDemoFadeOpenEnd(const al::LiveActor*);
bool isDemoFadeWipeStateEnableOpenMenuOrSnapShotMode(const al::Scene*);
void tryCreateDemoHackFirstDirector(al::LiveActor*, s32, const al::ActorInitInfo&);
void noticeDemoStartToDemoHackFirstDirector(const al::Scene*);
void setBossBarrierField(BarrierField*);
BarrierField* tryGetBossBarrierField(const al::LiveActor*);
void setDemoEnvironmentChangeFlag(const al::Scene*, bool);
void setDemoEnvironmentChangeFlag(const al::LiveActor*, bool);
bool isDemoEnvironmentChange(const al::Scene*);
bool isDemoEnvironmentChange(const al::LiveActor*);
s32 getRandomActionIndexDemoChangeWorld(const al::LiveActor*);
void setDemoInfoDemoName(const al::Scene*, const char*);
void getDemoInfoDemoName(const al::LiveActor*);
bool isTriggerDemoCancel(const al::IUseSceneObjHolder*);
void updateDemoSystemOnly(const al::Scene*);
void notifyDisableUpdateCamera(const al::LiveActor*);
bool isDisableUpdateCamera(const al::Scene*);
}  // namespace rs
