#pragma once

#include "Library/Base/StringUtil.h"
#include "Library/LiveActor/LiveActor.h"
#include "Player/PlayerFunction.h"
#include "Player/PlayerModelHolder.h"

namespace game {

class PlayerAnimator {
public:
    PlayerAnimator(PlayerModelHolder const* holder,al::ActorDitherAnimator *) : modelHolder(holder) {}
    void startAnim(const sead::SafeString& sName) {
        const char* name = sName.cstr();
        if(al::isEqualString(name, "AreaWait64")) maxFrame = 390;
        else if(al::isEqualString(name, "AreaWaitAloha")) maxFrame = 988;
        else if(al::isEqualString(name, "AreaWaitBalance")) maxFrame = 270;
        else if(al::isEqualString(name, "AreaWaitBeach")) maxFrame = 390;
        else if(al::isEqualString(name, "AreaWaitCold")) maxFrame = 36;
        else if(al::isEqualString(name, "AreaWaitDance01")) maxFrame = 144;
        else if(al::isEqualString(name, "AreaWaitDance02")) maxFrame = 240;
        else if(al::isEqualString(name, "AreaWaitDance03")) maxFrame = 240;
        else if(al::isEqualString(name, "AreaWaitFight")) maxFrame = 60;
        else if(al::isEqualString(name, "AreaWaitGetwarm")) maxFrame = 60;
        else if(al::isEqualString(name, "AreaWaitGuitar")) maxFrame = 624;
        else if(al::isEqualString(name, "AreaWaitHeatGround")) maxFrame = 28;
        else if(al::isEqualString(name, "AreaWaitHot")) maxFrame = 600;
        else if(al::isEqualString(name, "AreaWaitJog")) maxFrame = 34;
        else if(al::isEqualString(name, "AreaWaitLookUp")) maxFrame = 270;
        else if(al::isEqualString(name, "AreaWaitSayCheese")) maxFrame = 360;
        else if(al::isEqualString(name, "AreaWaitScared")) maxFrame = 270;
        else if(al::isEqualString(name, "AreaWaitSearch")) maxFrame = 360;
        else if(al::isEqualString(name, "AreaWaitSigh")) maxFrame = 200;
        else if(al::isEqualString(name, "AreaWaitSitDown")) maxFrame = 600;
        else if(al::isEqualString(name, "AreaWaitSleepy")) maxFrame = 200;
        else if(al::isEqualString(name, "AreaWaitSmell")) maxFrame = 280;
        else if(al::isEqualString(name, "AreaWaitStink")) maxFrame = 164;
        else if(al::isEqualString(name, "AreaWaitStretch")) maxFrame = 400;
        else if(al::isEqualString(name, "AreaWaitView")) maxFrame = 420;
        else if(al::isEqualString(name, "AreaWaitWaterfall")) maxFrame = 44;
        else if(al::isEqualString(name, "AreaWaitWonder")) maxFrame = 660;
        else if(al::isEqualString(name, "ArrowShoot")) maxFrame = 30;
        else if(al::isEqualString(name, "ArrowShootStart")) maxFrame = 29;
        else if(al::isEqualString(name, "BallToss")) maxFrame = 24;
        else if(al::isEqualString(name, "BallTossGround")) maxFrame = 24;
        else if(al::isEqualString(name, "BattleWait")) maxFrame = 160;
        else if(al::isEqualString(name, "BedSleep")) maxFrame = 120;
        else if(al::isEqualString(name, "BedSleepStart")) maxFrame = 608;
        else if(al::isEqualString(name, "BedSnooze")) maxFrame = 180;
        else if(al::isEqualString(name, "BedSnoozeStart")) maxFrame = 133;
        else if(al::isEqualString(name, "BikeRide")) maxFrame = 180;
        else if(al::isEqualString(name, "Bind")) maxFrame = 29;
        else if(al::isEqualString(name, "Brake")) maxFrame = 5;
        else if(al::isEqualString(name, "BubbleJump")) maxFrame = 28;
        else if(al::isEqualString(name, "BubbleStart")) maxFrame = 70;
        else if(al::isEqualString(name, "BubbleWait")) maxFrame = 90;
        else if(al::isEqualString(name, "CanoeDamage")) maxFrame = 80;
        else if(al::isEqualString(name, "CanoeDamageEnd")) maxFrame = 12;
        else if(al::isEqualString(name, "CanoeDamageStart")) maxFrame = 12;
        else if(al::isEqualString(name, "CanoePaddle")) maxFrame = 80;
        else if(al::isEqualString(name, "CanoeTurnL")) maxFrame = 40;
        else if(al::isEqualString(name, "CanoeTurnR")) maxFrame = 40;
        else if(al::isEqualString(name, "CanoeWait")) maxFrame = 120;
        else if(al::isEqualString(name, "Carry")) maxFrame = 60;
        else if(al::isEqualString(name, "CarryFront")) maxFrame = 60;
        else if(al::isEqualString(name, "CarryFrontStart")) maxFrame = 8;
        else if(al::isEqualString(name, "CarryFrontThrow")) maxFrame = 24;
        else if(al::isEqualString(name, "CarryUp")) maxFrame = 60;
        else if(al::isEqualString(name, "CarryUpStart")) maxFrame = 8;
        else if(al::isEqualString(name, "CarryUpThrow")) maxFrame = 24;
        else if(al::isEqualString(name, "CatapultStart")) maxFrame = 70;
        else if(al::isEqualString(name, "CatchCap")) maxFrame = 10;
        else if(al::isEqualString(name, "CatchCapJump")) maxFrame = 11;
        else if(al::isEqualString(name, "CatchCapJumpParts")) maxFrame = 12;
        else if(al::isEqualString(name, "CatchCapJumpPartsReverse")) maxFrame = 12;
        else if(al::isEqualString(name, "CatchCapParts")) maxFrame = 10;
        else if(al::isEqualString(name, "CatchKoopaCap")) maxFrame = 50;
        else if(al::isEqualString(name, "ClashWorldStandUp")) maxFrame = 88;
        else if(al::isEqualString(name, "ClimbTreeHandStandWait")) maxFrame = 120;
        else if(al::isEqualString(name, "Damage")) maxFrame = 92;
        else if(al::isEqualString(name, "DamageLand")) maxFrame = 78;
        else if(al::isEqualString(name, "DamageSwim")) maxFrame = 140;
        else if(al::isEqualString(name, "DamageSwimSurface")) maxFrame = 53;
        else if(al::isEqualString(name, "DamageSwimSurfaceLand")) maxFrame = 145;
        else if(al::isEqualString(name, "DamageWait")) maxFrame = 120;
        else if(al::isEqualString(name, "Dash")) maxFrame = 17;
        else if(al::isEqualString(name, "DashBrake")) maxFrame = 5;
        else if(al::isEqualString(name, "DashFast")) maxFrame = 14;
        else if(al::isEqualString(name, "DashTurn")) maxFrame = 12;
        else if(al::isEqualString(name, "Dead")) maxFrame = 190;
        else if(al::isEqualString(name, "Dead01")) maxFrame = 190;
        else if(al::isEqualString(name, "Dead02")) maxFrame = 190;
        else if(al::isEqualString(name, "Dead03")) maxFrame = 190;
        else if(al::isEqualString(name, "Dead04")) maxFrame = 190;
        else if(al::isEqualString(name, "DeadFall")) maxFrame = 180;
        else if(al::isEqualString(name, "DeadFire")) maxFrame = 190;
        else if(al::isEqualString(name, "DeadIce")) maxFrame = 190;
        else if(al::isEqualString(name, "DeadPoison")) maxFrame = 190;
        else if(al::isEqualString(name, "DeadSand")) maxFrame = 190;
        else if(al::isEqualString(name, "DeadWallow")) maxFrame = 264;
        else if(al::isEqualString(name, "DeadWater")) maxFrame = 264;
        else if(al::isEqualString(name, "DemoAppearFromHome")) maxFrame = 240;
        else if(al::isEqualString(name, "DemoBattleEndGiantWanderBoss")) maxFrame = 758;
        else if(al::isEqualString(name, "DemoBattleStartBossKnuckle")) maxFrame = 1090;
        else if(al::isEqualString(name, "DemoBattleStartBreeda")) maxFrame = 540;
        else if(al::isEqualString(name, "DemoBattleStartBreedaFirst")) maxFrame = 502;
        else if(al::isEqualString(name, "DemoBattleStartGolemClimb")) maxFrame = 1370;
        else if(al::isEqualString(name, "DemoBossRaidAttack")) maxFrame = 3124;
        else if(al::isEqualString(name, "DemoCrashHome")) maxFrame = 2229;
        else if(al::isEqualString(name, "DemoCrashHomeFall")) maxFrame = 2572;
        else if(al::isEqualString(name, "DemoEnding01")) maxFrame = 2145;
        else if(al::isEqualString(name, "DemoEnding02")) maxFrame = 2184;
        else if(al::isEqualString(name, "DemoEnding03")) maxFrame = 1406;
        else if(al::isEqualString(name, "DemoEnding04")) maxFrame = 390;
        else if(al::isEqualString(name, "DemoEnterChurch")) maxFrame = 520;
        else if(al::isEqualString(name, "DemoGetShine")) maxFrame = 125;
        else if(al::isEqualString(name, "DemoGetShineCloseUp")) maxFrame = 144;
        else if(al::isEqualString(name, "DemoGetShineEnd")) maxFrame = 92;
        else if(al::isEqualString(name, "DemoGetShineGrandCloseUp")) maxFrame = 150;
        else if(al::isEqualString(name, "DemoGetShineGrandCloseUpEnd")) maxFrame = 0;
        else if(al::isEqualString(name, "DemoGetShineGrandEnd")) maxFrame = 247;
        else if(al::isEqualString(name, "DemoGetShineGrandStart")) maxFrame = 632;
        else if(al::isEqualString(name, "DemoGetShineLand")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoGetShinePaper")) maxFrame = 125;
        else if(al::isEqualString(name, "DemoGetShineRock")) maxFrame = 125;
        else if(al::isEqualString(name, "DemoGetShineScissors")) maxFrame = 125;
        else if(al::isEqualString(name, "DemoGetShineStart")) maxFrame = 240;
        else if(al::isEqualString(name, "DemoHackFirst")) maxFrame = 2262;
        else if(al::isEqualString(name, "DemoHackKoopa01")) maxFrame = 450;
        else if(al::isEqualString(name, "DemoHackKoopa02")) maxFrame = 916;
        else if(al::isEqualString(name, "DemoJangoCapSearch")) maxFrame = 140;
        else if(al::isEqualString(name, "DemoJangoGetUp")) maxFrame = 60;
        else if(al::isEqualString(name, "DemoJangoLookAround")) maxFrame = 140;
        else if(al::isEqualString(name, "DemoJangoStolen")) maxFrame = 112;
        else if(al::isEqualString(name, "DemoJangoStolenLoop")) maxFrame = 60;
        else if(al::isEqualString(name, "DemoMeetCapNpcC01")) maxFrame = 530;
        else if(al::isEqualString(name, "DemoMeetCapNpcC01TalkWait")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoMeetCapNpcC02")) maxFrame = 131;
        else if(al::isEqualString(name, "DemoMeetCapNpcC02ATalkWait")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoMeetCapNpcC02BTalkWait")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoMeetCapNpcC03")) maxFrame = 198;
        else if(al::isEqualString(name, "DemoMeetCapNpcC04TalkWait")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoMeetCapNpcC06TalkWait")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoMeetCapNpcC07TalkWait")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoMeetCapNpcC08TalkWait")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoMeetCapNpcC10A")) maxFrame = 541;
        else if(al::isEqualString(name, "DemoMeetCapNpcC10ATalkWait")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoMeetCapNpcC10B")) maxFrame = 850;
        else if(al::isEqualString(name, "DemoMeetCapNpcC10BTalkWait")) maxFrame = 110;
        else if(al::isEqualString(name, "DemoOpening01")) maxFrame = 5408;
        else if(al::isEqualString(name, "DemoOpeningCap")) maxFrame = 90;
        else if(al::isEqualString(name, "DemoOpeningDown")) maxFrame = 120;
        else if(al::isEqualString(name, "DemoPayToHome")) maxFrame = 380;
        else if(al::isEqualString(name, "DemoReset")) maxFrame = 180;
        else if(al::isEqualString(name, "DemoReturnToHome")) maxFrame = 299;
        else if(al::isEqualString(name, "DemoSitDownTalk")) maxFrame = 840;
        else if(al::isEqualString(name, "DemoSitDownWaitFirst")) maxFrame = 420;
        else if(al::isEqualString(name, "DemoStartJango")) maxFrame = 800;
        else if(al::isEqualString(name, "DemoStartJango2")) maxFrame = 600;
        else if(al::isEqualString(name, "DemoStartUpHome")) maxFrame = 699;
        else if(al::isEqualString(name, "DemoStartUpHomeSky")) maxFrame = 3155;
        else if(al::isEqualString(name, "DemoStartWaterfall")) maxFrame = 1135;
        else if(al::isEqualString(name, "DemoTakeOffKoopaForMoon")) maxFrame = 2999;
        else if(al::isEqualString(name, "DemoTalkCapManHeroAppear")) maxFrame = 36;
        else if(al::isEqualString(name, "DemoTalkCapManHeroWalk")) maxFrame = 140;
        else if(al::isEqualString(name, "DemoWarpEnd")) maxFrame = 30;
        else if(al::isEqualString(name, "DemoWarpStart")) maxFrame = 28;
        else if(al::isEqualString(name, "DemoWorldLavaScenario1End")) maxFrame = 1454;
        else if(al::isEqualString(name, "DemoWorldMoveBackward")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveBackward1")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveBackward2")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveBackward3")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveForward")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveForwardArrive")) maxFrame = 240;
        else if(al::isEqualString(name, "DemoWorldMoveForwardNormal1")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveForwardNormal2")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveForwardNormal3")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveMoonBackward")) maxFrame = 890;
        else if(al::isEqualString(name, "DemoWorldMoveMoonForward")) maxFrame = 1560;
        else if(al::isEqualString(name, "DemoWorldMoveMoonForwardFirst")) maxFrame = 1560;
        else if(al::isEqualString(name, "DemoWorldTakeoff")) maxFrame = 311;
        else if(al::isEqualString(name, "DemoWorldTakeoffEast")) maxFrame = 400;
        else if(al::isEqualString(name, "DemoWorldTakeoffForMoon")) maxFrame = 480;
        else if(al::isEqualString(name, "DemoWorldTakeoffForMoonFirst")) maxFrame = 1475;
        else if(al::isEqualString(name, "DemoWorldTakeoffForMoonFirstTuxedo")) maxFrame = 1475;
        else if(al::isEqualString(name, "DemoWorldTakeoffWest")) maxFrame = 400;
        else if(al::isEqualString(name, "DemoWorldWarpHole01")) maxFrame = 229;
        else if(al::isEqualString(name, "DemoWorldWarpHole02")) maxFrame = 360;
        else if(al::isEqualString(name, "DemoWorldWarpHole03")) maxFrame = 310;
        else if(al::isEqualString(name, "Dive")) maxFrame = 29;
        else if(al::isEqualString(name, "DiveInWater")) maxFrame = 48;
        else if(al::isEqualString(name, "DokanIn")) maxFrame = 54;
        else if(al::isEqualString(name, "DokanInHome")) maxFrame = 46;
        else if(al::isEqualString(name, "DokanInUpsideDown")) maxFrame = 20;
        else if(al::isEqualString(name, "DokanJump")) maxFrame = 58;
        else if(al::isEqualString(name, "DokanOut")) maxFrame = 21;
        else if(al::isEqualString(name, "DokanOutUpsideDown")) maxFrame = 20;
        else if(al::isEqualString(name, "DokanReady")) maxFrame = 4;
        else if(al::isEqualString(name, "DokanReadyHome")) maxFrame = 4;
        else if(al::isEqualString(name, "DokanSideIn")) maxFrame = 56;
        else if(al::isEqualString(name, "DokanSideOut")) maxFrame = 58;
        else if(al::isEqualString(name, "DoorIn")) maxFrame = 88;
        else if(al::isEqualString(name, "DoorOut")) maxFrame = 58;
        else if(al::isEqualString(name, "DoorStart")) maxFrame = 9;
        else if(al::isEqualString(name, "Fall")) maxFrame = 28;
        else if(al::isEqualString(name, "Fire")) maxFrame = 22;
        else if(al::isEqualString(name, "FireRun")) maxFrame = 60;
        else if(al::isEqualString(name, "FireRunStart")) maxFrame = 88;
        else if(al::isEqualString(name, "GetShine")) maxFrame = 12;
        else if(al::isEqualString(name, "GetShineCity")) maxFrame = 40;
        else if(al::isEqualString(name, "GetShineEmpty")) maxFrame = 40;
        else if(al::isEqualString(name, "GetShineGrand")) maxFrame = 12;
        else if(al::isEqualString(name, "GetShineSub")) maxFrame = 1;
        else if(al::isEqualString(name, "GrabCeilJump")) maxFrame = 46;
        else if(al::isEqualString(name, "GrabCeilStart")) maxFrame = 51;
        else if(al::isEqualString(name, "GrabCeilSwing")) maxFrame = 120;
        else if(al::isEqualString(name, "GrabCeilWait")) maxFrame = 90;
        else if(al::isEqualString(name, "Hack")) maxFrame = 20;
        else if(al::isEqualString(name, "HeadSliding")) maxFrame = 20;
        else if(al::isEqualString(name, "HeadSlidingStart")) maxFrame = 48;
        else if(al::isEqualString(name, "HipDrop")) maxFrame = 10;
        else if(al::isEqualString(name, "HipDropLand")) maxFrame = 44;
        else if(al::isEqualString(name, "HipDropReaction")) maxFrame = 11;
        else if(al::isEqualString(name, "HipDropStart")) maxFrame = 24;
        else if(al::isEqualString(name, "HomeCapManHeroAppear")) maxFrame = 36;
        else if(al::isEqualString(name, "Jump")) maxFrame = 84;
        else if(al::isEqualString(name, "Jump2")) maxFrame = 42;
        else if(al::isEqualString(name, "Jump3")) maxFrame = 68;
        else if(al::isEqualString(name, "JumpBack")) maxFrame = 68;
        else if(al::isEqualString(name, "JumpBroad")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpBroad2")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpBroad3")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpBroad4")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpBroad5")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpBroad6")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpBroad7")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpBroad8")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpBroad9")) maxFrame = 38;
        else if(al::isEqualString(name, "JumpCapCatchCommon")) maxFrame = 27;
        else if(al::isEqualString(name, "JumpCapLeapFrog")) maxFrame = 36;
        else if(al::isEqualString(name, "JumpDashFast")) maxFrame = 30;
        else if(al::isEqualString(name, "JumpEndHack")) maxFrame = 46;
        else if(al::isEqualString(name, "JumpFlap")) maxFrame = 30;
        else if(al::isEqualString(name, "JumpHipDrop")) maxFrame = 46;
        else if(al::isEqualString(name, "JumpInterp")) maxFrame = 84;
        else if(al::isEqualString(name, "JumpNpcTrample")) maxFrame = 54;
        else if(al::isEqualString(name, "JumpObjectReaction")) maxFrame = 74;
        else if(al::isEqualString(name, "JumpReverse")) maxFrame = 84;
        else if(al::isEqualString(name, "JumpReverseInterp")) maxFrame = 84;
        else if(al::isEqualString(name, "JumpTurn")) maxFrame = 60;
        else if(al::isEqualString(name, "Kick")) maxFrame = 24;
        else if(al::isEqualString(name, "KoopaCapPunchFinishL")) maxFrame = 143;
        else if(al::isEqualString(name, "KoopaCapPunchFinishLStart")) maxFrame = 6;
        else if(al::isEqualString(name, "KoopaCapPunchFinishR")) maxFrame = 143;
        else if(al::isEqualString(name, "KoopaCapPunchFinishRStart")) maxFrame = 6;
        else if(al::isEqualString(name, "KoopaCapPunchL")) maxFrame = 19;
        else if(al::isEqualString(name, "KoopaCapPunchLStart")) maxFrame = 6;
        else if(al::isEqualString(name, "KoopaCapPunchR")) maxFrame = 19;
        else if(al::isEqualString(name, "KoopaCapPunchRStart")) maxFrame = 6;
        else if(al::isEqualString(name, "KoopaDemoBattleStartChurchFirstLv2")) maxFrame = 1100;
        else if(al::isEqualString(name, "KoopaDemoBattleStartChurchLv2")) maxFrame = 1975;
        else if(al::isEqualString(name, "KoopaDemoBattleStartChurchSecondLv2")) maxFrame = 394;
        else if(al::isEqualString(name, "KoopaDemoBattleStartFirstLv1")) maxFrame = 790;
        else if(al::isEqualString(name, "KoopaDemoBattleStartFirstLv2")) maxFrame = 790;
        else if(al::isEqualString(name, "KoopaDemoBattleStartSecondLv1")) maxFrame = 1340;
        else if(al::isEqualString(name, "KoopaDemoBattleStartSecondLv2")) maxFrame = 880;
        else if(al::isEqualString(name, "KoopaDemoBattleStartTalkBlendLv1")) maxFrame = 119;
        else if(al::isEqualString(name, "KoopaDemoClashBasement")) maxFrame = 1421;
        else if(al::isEqualString(name, "Land")) maxFrame = 26;
        else if(al::isEqualString(name, "LandDownFall")) maxFrame = 34;
        else if(al::isEqualString(name, "LandJump3")) maxFrame = 70;
        else if(al::isEqualString(name, "LandRolling")) maxFrame = 36;
        else if(al::isEqualString(name, "LandStiffen")) maxFrame = 120;
        else if(al::isEqualString(name, "LandTurn")) maxFrame = 26;
        else if(al::isEqualString(name, "MainScenarioCameraWait")) maxFrame = 80;
        else if(al::isEqualString(name, "MofumofuDemoOpening1")) maxFrame = 1230;
        else if(al::isEqualString(name, "MofumofuDemoOpening2")) maxFrame = 594;
        else if(al::isEqualString(name, "MotorcycleRideC")) maxFrame = 180;
        else if(al::isEqualString(name, "MotorcycleRideClashC")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideClashL")) maxFrame = 17;
        else if(al::isEqualString(name, "MotorcycleRideClashR")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideJumpC")) maxFrame = 40;
        else if(al::isEqualString(name, "MotorcycleRideJumpL")) maxFrame = 40;
        else if(al::isEqualString(name, "MotorcycleRideJumpR")) maxFrame = 40;
        else if(al::isEqualString(name, "MotorcycleRideL")) maxFrame = 180;
        else if(al::isEqualString(name, "MotorcycleRideLandC")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideLandL")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideLandR")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideOn")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideR")) maxFrame = 180;
        else if(al::isEqualString(name, "MotorcycleRideRunStartC")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideRunStartL")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideRunStartR")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideStart")) maxFrame = 20;
        else if(al::isEqualString(name, "MotorcycleRideStartL")) maxFrame = 6;
        else if(al::isEqualString(name, "MotorcycleRideStartR")) maxFrame = 6;
        else if(al::isEqualString(name, "MotorcycleWait")) maxFrame = 180;
        else if(al::isEqualString(name, "OpeningStandUp")) maxFrame = 196;
        else if(al::isEqualString(name, "PauseMenu2Player")) maxFrame = 990;
        else if(al::isEqualString(name, "PauseMenuContinue")) maxFrame = 1320;
        else if(al::isEqualString(name, "PauseMenuContinueEnd")) maxFrame = 8;
        else if(al::isEqualString(name, "PauseMenuData")) maxFrame = 990;
        else if(al::isEqualString(name, "PauseMenuHelp")) maxFrame = 640;
        else if(al::isEqualString(name, "PauseMenuNewGame")) maxFrame = 1112;
        else if(al::isEqualString(name, "PauseMenuSave")) maxFrame = 770;
        else if(al::isEqualString(name, "PauseMenuStart")) maxFrame = 98;
        else if(al::isEqualString(name, "PauseMenuWait")) maxFrame = 1112;
        else if(al::isEqualString(name, "PoleCatch")) maxFrame = 8;
        else if(al::isEqualString(name, "PoleClimb")) maxFrame = 25;
        else if(al::isEqualString(name, "PoleFall")) maxFrame = 21;
        else if(al::isEqualString(name, "PoleHandStandEnd")) maxFrame = 24;
        else if(al::isEqualString(name, "PoleHandStandJump")) maxFrame = 63;
        else if(al::isEqualString(name, "PoleHandStandStart")) maxFrame = 32;
        else if(al::isEqualString(name, "PoleHandStandTurn")) maxFrame = 23;
        else if(al::isEqualString(name, "PoleHandStandWait")) maxFrame = 120;
        else if(al::isEqualString(name, "PoleTurn")) maxFrame = 50;
        else if(al::isEqualString(name, "PoleWait")) maxFrame = 180;
        else if(al::isEqualString(name, "Punch")) maxFrame = 23;
        else if(al::isEqualString(name, "Push")) maxFrame = 60;
        else if(al::isEqualString(name, "RabbitGet")) maxFrame = 26;
        else if(al::isEqualString(name, "RaceManHack")) maxFrame = 20;
        else if(al::isEqualString(name, "RaceManHackEnd")) maxFrame = 30;
        else if(al::isEqualString(name, "RaceManHackStart")) maxFrame = 30;
        else if(al::isEqualString(name, "RaceManJumpEnd")) maxFrame = 46;
        else if(al::isEqualString(name, "RaceManJumpStart")) maxFrame = 14;
        else if(al::isEqualString(name, "RaceManResultLose")) maxFrame = 120;
        else if(al::isEqualString(name, "RaceManResultWin")) maxFrame = 58;
        else if(al::isEqualString(name, "RaceResultLose")) maxFrame = 602;
        else if(al::isEqualString(name, "RaceResultWin")) maxFrame = 100;
        else if(al::isEqualString(name, "ReactionCapOn")) maxFrame = 52;
        else if(al::isEqualString(name, "Rolling")) maxFrame = 9;
        else if(al::isEqualString(name, "RollingEnd")) maxFrame = 12;
        else if(al::isEqualString(name, "RollingEndBackUp")) maxFrame = 12;
        else if(al::isEqualString(name, "RollingJump")) maxFrame = 28;
        else if(al::isEqualString(name, "RollingLand")) maxFrame = 20;
        else if(al::isEqualString(name, "RollingStandUp")) maxFrame = 9;
        else if(al::isEqualString(name, "RollingStart")) maxFrame = 6;
        else if(al::isEqualString(name, "RoswellPut")) maxFrame = 2;
        else if(al::isEqualString(name, "RoswellRun")) maxFrame = 20;
        else if(al::isEqualString(name, "RoswellThrow")) maxFrame = 22;
        else if(al::isEqualString(name, "RoswellWait")) maxFrame = 360;
        else if(al::isEqualString(name, "Run")) maxFrame = 17;
        else if(al::isEqualString(name, "RunMoon")) maxFrame = 17;
        else if(al::isEqualString(name, "RunStart")) maxFrame = 30;
        else if(al::isEqualString(name, "SandWaitNormal")) maxFrame = 80;
        else if(al::isEqualString(name, "SandWaitStrong")) maxFrame = 30;
        else if(al::isEqualString(name, "SandWalkNormal")) maxFrame = 60;
        else if(al::isEqualString(name, "SandWalkStrong")) maxFrame = 30;
        else if(al::isEqualString(name, "SitDown")) maxFrame = 420;
        else if(al::isEqualString(name, "SitDownEnd")) maxFrame = 39;
        else if(al::isEqualString(name, "SitDownLand")) maxFrame = 26;
        else if(al::isEqualString(name, "SitDownSleep")) maxFrame = 180;
        else if(al::isEqualString(name, "SitDownSleepEnd")) maxFrame = 88;
        else if(al::isEqualString(name, "SitDownSleepStart")) maxFrame = 134;
        else if(al::isEqualString(name, "SitDownStart")) maxFrame = 45;
        else if(al::isEqualString(name, "Sleep")) maxFrame = 120;
        else if(al::isEqualString(name, "SleepStart")) maxFrame = 608;
        else if(al::isEqualString(name, "Slide")) maxFrame = 198;
        else if(al::isEqualString(name, "SlopeSlide")) maxFrame = 34;
        else if(al::isEqualString(name, "SlopeSlideBack")) maxFrame = 10;
        else if(al::isEqualString(name, "Snooze")) maxFrame = 180;
        else if(al::isEqualString(name, "SnoozeStart")) maxFrame = 507;
        else if(al::isEqualString(name, "SphinxRideClash")) maxFrame = 34;
        else if(al::isEqualString(name, "SphinxRideFall")) maxFrame = 24;
        else if(al::isEqualString(name, "SphinxRideGetOn")) maxFrame = 34;
        else if(al::isEqualString(name, "SphinxRideJump")) maxFrame = 24;
        else if(al::isEqualString(name, "SphinxRideJumpStart")) maxFrame = 20;
        else if(al::isEqualString(name, "SphinxRideOn")) maxFrame = 20;
        else if(al::isEqualString(name, "SphinxRideRide")) maxFrame = 42;
        else if(al::isEqualString(name, "SphinxRideRideOn")) maxFrame = 4;
        else if(al::isEqualString(name, "SphinxRideRideStartL")) maxFrame = 10;
        else if(al::isEqualString(name, "SphinxRideRideStartR")) maxFrame = 10;
        else if(al::isEqualString(name, "SphinxRideRunSlow")) maxFrame = 32;
        else if(al::isEqualString(name, "SphinxRideStop")) maxFrame = 14;
        else if(al::isEqualString(name, "SphinxRideStopStart")) maxFrame = 38;
        else if(al::isEqualString(name, "SpinCap")) maxFrame = 12;
        else if(al::isEqualString(name, "SpinCapAirStart")) maxFrame = 72;
        else if(al::isEqualString(name, "SpinCapAirStartCapCatch")) maxFrame = 20;
        else if(al::isEqualString(name, "SpinCapAirStartDoubleDown")) maxFrame = 28;
        else if(al::isEqualString(name, "SpinCapAirStartDoubleLeft")) maxFrame = 72;
        else if(al::isEqualString(name, "SpinCapAirStartDoubleRight")) maxFrame = 72;
        else if(al::isEqualString(name, "SpinCapAirStartDoubleUp")) maxFrame = 26;
        else if(al::isEqualString(name, "SpinCapAirStartLeft")) maxFrame = 70;
        else if(al::isEqualString(name, "SpinCapAirStartLong")) maxFrame = 22;
        else if(al::isEqualString(name, "SpinCapAirStartRight")) maxFrame = 70;
        else if(al::isEqualString(name, "SpinCapEnd")) maxFrame = 12;
        else if(al::isEqualString(name, "SpinCapJumpStart")) maxFrame = 72;
        else if(al::isEqualString(name, "SpinCapStart")) maxFrame = 22;
        else if(al::isEqualString(name, "SpinCapStart2Left")) maxFrame = 32;
        else if(al::isEqualString(name, "SpinCapStart2Right")) maxFrame = 32;
        else if(al::isEqualString(name, "SpinCapStart3Left")) maxFrame = 42;
        else if(al::isEqualString(name, "SpinCapStart3Right")) maxFrame = 42;
        else if(al::isEqualString(name, "SpinCapStartCapCatch")) maxFrame = 20;
        else if(al::isEqualString(name, "SpinCapStartDoubleDown")) maxFrame = 26;
        else if(al::isEqualString(name, "SpinCapStartDoubleLeft")) maxFrame = 44;
        else if(al::isEqualString(name, "SpinCapStartDoubleRight")) maxFrame = 44;
        else if(al::isEqualString(name, "SpinCapStartDoubleUp")) maxFrame = 26;
        else if(al::isEqualString(name, "SpinCapStartLeft")) maxFrame = 17;
        else if(al::isEqualString(name, "SpinCapStartLong")) maxFrame = 22;
        else if(al::isEqualString(name, "SpinCapStartRight")) maxFrame = 17;
        else if(al::isEqualString(name, "SpinCapStartRolling")) maxFrame = 22;
        else if(al::isEqualString(name, "SpinCapWait")) maxFrame = 80;
        else if(al::isEqualString(name, "SpinGroundL")) maxFrame = 10;
        else if(al::isEqualString(name, "SpinGroundR")) maxFrame = 10;
        else if(al::isEqualString(name, "SpinJump")) maxFrame = 29;
        else if(al::isEqualString(name, "SpinJumpDownFall")) maxFrame = 10;
        else if(al::isEqualString(name, "SpinJumpDownFallL")) maxFrame = 10;
        else if(al::isEqualString(name, "SpinJumpDownFallR")) maxFrame = 10;
        else if(al::isEqualString(name, "SpinJumpL")) maxFrame = 8;
        else if(al::isEqualString(name, "SpinJumpLoop")) maxFrame = 23;
        else if(al::isEqualString(name, "SpinJumpR")) maxFrame = 8;
        else if(al::isEqualString(name, "SpinJumpStart")) maxFrame = 26;
        else if(al::isEqualString(name, "SpinSeparate")) maxFrame = 32;
        else if(al::isEqualString(name, "SpinSeparateSwim")) maxFrame = 48;
        else if(al::isEqualString(name, "SquatEnd")) maxFrame = 13;
        else if(al::isEqualString(name, "SquatLand")) maxFrame = 26;
        else if(al::isEqualString(name, "SquatStart")) maxFrame = 3;
        else if(al::isEqualString(name, "SquatWait")) maxFrame = 120;
        else if(al::isEqualString(name, "SquatWalk")) maxFrame = 36;
        else if(al::isEqualString(name, "StabStart")) maxFrame = 16;
        else if(al::isEqualString(name, "StabUndarWait")) maxFrame = 80;
        else if(al::isEqualString(name, "StabUnderStart")) maxFrame = 20;
        else if(al::isEqualString(name, "StabWait")) maxFrame = 80;
        else if(al::isEqualString(name, "StabWallWait")) maxFrame = 80;
        else if(al::isEqualString(name, "SwimDieOver")) maxFrame = 190;
        else if(al::isEqualString(name, "SwimDive")) maxFrame = 119;
        else if(al::isEqualString(name, "SwimFallIn")) maxFrame = 32;
        else if(al::isEqualString(name, "SwimHeadSliding")) maxFrame = 20;
        else if(al::isEqualString(name, "SwimHeadSlidingEnd")) maxFrame = 30;
        else if(al::isEqualString(name, "SwimHeadSlidingIn")) maxFrame = 20;
        else if(al::isEqualString(name, "SwimHeadSlidingStart")) maxFrame = 48;
        else if(al::isEqualString(name, "SwimHipDrop")) maxFrame = 24;
        else if(al::isEqualString(name, "SwimHipDropLand")) maxFrame = 74;
        else if(al::isEqualString(name, "SwimHipDropStart")) maxFrame = 30;
        else if(al::isEqualString(name, "SwimJumpHipDrop")) maxFrame = 124;
        else if(al::isEqualString(name, "SwimLand")) maxFrame = 45;
        else if(al::isEqualString(name, "SwimSpinCapStart")) maxFrame = 50;
        else if(al::isEqualString(name, "SwimSpinCapStartDoubleDown")) maxFrame = 38;
        else if(al::isEqualString(name, "SwimSpinCapStartDoubleLeft")) maxFrame = 70;
        else if(al::isEqualString(name, "SwimSpinCapStartDoubleRight")) maxFrame = 70;
        else if(al::isEqualString(name, "SwimSpinCapStartDoubleUp")) maxFrame = 40;
        else if(al::isEqualString(name, "SwimSpinCapStartLeft")) maxFrame = 50;
        else if(al::isEqualString(name, "SwimSpinCapStartRight")) maxFrame = 50;
        else if(al::isEqualString(name, "SwimSquat")) maxFrame = 80;
        else if(al::isEqualString(name, "SwimSquatWalk")) maxFrame = 54;
        else if(al::isEqualString(name, "SwimStand")) maxFrame = 32;
        else if(al::isEqualString(name, "SwimStandMove")) maxFrame = 70;
        else if(al::isEqualString(name, "SwimStandSurface")) maxFrame = 46;
        else if(al::isEqualString(name, "SwimStandWait")) maxFrame = 140;
        else if(al::isEqualString(name, "SwimSurface")) maxFrame = 38;
        else if(al::isEqualString(name, "SwimTalkWait")) maxFrame = 118;
        else if(al::isEqualString(name, "SwimTrample")) maxFrame = 70;
        else if(al::isEqualString(name, "SwimTrampoline")) maxFrame = 58;
        else if(al::isEqualString(name, "SwimWait")) maxFrame = 118;
        else if(al::isEqualString(name, "SwimWalk")) maxFrame = 68;
        else if(al::isEqualString(name, "TalkEnd")) maxFrame = 14;
        else if(al::isEqualString(name, "TalkTurn")) maxFrame = 60;
        else if(al::isEqualString(name, "TalkTurnL90")) maxFrame = 48;
        else if(al::isEqualString(name, "TalkTurnR90")) maxFrame = 48;
        else if(al::isEqualString(name, "TalkWait")) maxFrame = 692;
        else if(al::isEqualString(name, "TestDemoDiverA")) maxFrame = 1574;
        else if(al::isEqualString(name, "TestDemoDiverB")) maxFrame = 1060;
        else if(al::isEqualString(name, "TestDemoE3001")) maxFrame = 1815;
        else if(al::isEqualString(name, "TestRunBack")) maxFrame = 60;
        else if(al::isEqualString(name, "TestRunFront")) maxFrame = 60;
        else if(al::isEqualString(name, "TestRunLeft")) maxFrame = 60;
        else if(al::isEqualString(name, "TestRunRight")) maxFrame = 60;
        else if(al::isEqualString(name, "TestRunWait")) maxFrame = 60;
        else if(al::isEqualString(name, "ThrowCap")) maxFrame = 20;
        else if(al::isEqualString(name, "ThrowCapJump")) maxFrame = 18;
        else if(al::isEqualString(name, "ThrowCapJumpParts")) maxFrame = 16;
        else if(al::isEqualString(name, "ThrowCapParts")) maxFrame = 16;
        else if(al::isEqualString(name, "TouchJump")) maxFrame = 13;
        else if(al::isEqualString(name, "TouchJumpLong")) maxFrame = 13;
        else if(al::isEqualString(name, "TouchJumpLongSign")) maxFrame = 60;
        else if(al::isEqualString(name, "TractorBubbleEmd")) maxFrame = 60;
        else if(al::isEqualString(name, "TractorBubbleEnd")) maxFrame = 60;
        else if(al::isEqualString(name, "TractorBubbleStart")) maxFrame = 60;
        else if(al::isEqualString(name, "TractorBubbleWait")) maxFrame = 426;
        else if(al::isEqualString(name, "TreeClimb")) maxFrame = 25;
        else if(al::isEqualString(name, "TreeFall")) maxFrame = 21;
        else if(al::isEqualString(name, "Turn")) maxFrame = 12;
        else if(al::isEqualString(name, "TurnPoint")) maxFrame = 30;
        else if(al::isEqualString(name, "TurnStep")) maxFrame = 12;
        else if(al::isEqualString(name, "Wait")) maxFrame = 180;
        else if(al::isEqualString(name, "WaitCold")) maxFrame = 410;
        else if(al::isEqualString(name, "WaitDemo")) maxFrame = 180;
        else if(al::isEqualString(name, "WaitDigPoint")) maxFrame = 360;
        else if(al::isEqualString(name, "WaitHot")) maxFrame = 340;
        else if(al::isEqualString(name, "WaitRelax")) maxFrame = 1200;
        else if(al::isEqualString(name, "WaitRelaxStart")) maxFrame = 150;
        else if(al::isEqualString(name, "WaitVeryCold")) maxFrame = 36;
        else if(al::isEqualString(name, "Walk")) maxFrame = 60;
        else if(al::isEqualString(name, "WalkDemo")) maxFrame = 20;
        else if(al::isEqualString(name, "WalkSoft")) maxFrame = 60;
        else if(al::isEqualString(name, "WallCatch")) maxFrame = 79;
        else if(al::isEqualString(name, "WallCatchEnd")) maxFrame = 46;
        else if(al::isEqualString(name, "WallCatchEndFast")) maxFrame = 34;
        else if(al::isEqualString(name, "WallCatchEndJump")) maxFrame = 30;
        else if(al::isEqualString(name, "WallCatchMoveL")) maxFrame = 20;
        else if(al::isEqualString(name, "WallCatchMoveR")) maxFrame = 20;
        else if(al::isEqualString(name, "WallCatchStart")) maxFrame = 55;
        else if(al::isEqualString(name, "WallJump")) maxFrame = 37;
        else if(al::isEqualString(name, "WallKeep")) maxFrame = 26;
        else if(al::isEqualString(name, "WallKeepReverse")) maxFrame = 26;
        else if(al::isEqualString(name, "WallLand")) maxFrame = 24;
        else if(al::isEqualString(name, "WallSlideL")) maxFrame = 48;
        else if(al::isEqualString(name, "WallSlideR")) maxFrame = 48;
        else if(al::isEqualString(name, "WarpIn")) maxFrame = 54;
        else if(al::isEqualString(name, "WarpOut")) maxFrame = 21;
        else if(al::isEqualString(name, "WarpWait")) maxFrame = 1;
        else if(al::isEqualString(name, "WaterRoadMove")) maxFrame = 180;
        else if(al::isEqualString(name, "WearEnd")) maxFrame = 148;
        else if(al::isEqualString(name, "WhipAttackEnd")) maxFrame = 12;
        else if(al::isEqualString(name, "WhipAttackStart")) maxFrame = 15;
        else if(al::isEqualString(name, "WhipAttackWait")) maxFrame = 60;
        else if(al::isEqualString(name, "WhipWait")) maxFrame = 90;
        else if(al::isEqualString(name, "WorldWarpBind")) maxFrame = 90;
        else if(al::isEqualString(name, "WorldWarpBindStart")) maxFrame = 40;
        else if(al::isEqualString(name, "WorldWarpIn")) maxFrame = 70;
        else if(al::isEqualString(name, "WorldWarpOut")) maxFrame = 24;

        // special ones from ActionAnimCtrl
        else if(al::isEqualString(name, "StartSpinJumpL")) maxFrame = 8;
        else if(al::isEqualString(name, "StartSpinJumpR")) maxFrame = 8;
        else if(al::isEqualString(name, "RestartSpinJumpL")) maxFrame = 8;
        else if(al::isEqualString(name, "RestartSpinJumpR")) maxFrame = 8;
        else if(al::isEqualString(name, "DamageDown")) maxFrame = 92;
        else {
            printf("unknown animation: %s\n", name);
            CRASH
        }
        currentFrame = 0;
        currentAnim = name;
    }
    void startAnimDead() {
        // should be randomized, doesn't matter here
        startAnim("Dead01");
    }
    bool isAnimEnd() {
        return currentFrame >= maxFrame;
    }
    void updateAnimFrame() {
        currentFrame += 1;
    }
    bool isAnim(const sead::SafeString& name) const {
        if(currentAnim == nullptr) return false;
        return al::isEqualString(name.cstr(), currentAnim);
    }

    void setAnimFrame(f32 frame) {
        currentFrame = frame;
    }
    f32 getAnimFrame() const {
        return currentFrame;
    }
    f32 getAnimFrameMax() {
        return maxFrame;
    }

public:
    f32 currentFrame = 0.0f;
    f32 maxFrame = 0.0f;
    const char* currentAnim = nullptr;
    const PlayerModelHolder* modelHolder;


// stuff required for matching original signatures/calls
public:
    f32 getModelAlpha() { return 1.0f; }
    void endSubAnim() {}
    bool isUpperBodyAnimAttached() { return false; }
    void clearUpperBodyAnim() {}
    void startAnimSpinAttack(const sead::SafeString& a1) { startAnim(a1); }
    void startSubAnim(const sead::SafeString& a1) {}
    void startSubAnimOnlyAir(const sead::SafeString& a1) {}
    bool isSubAnim(const sead::SafeString& a1) const { return false; }
    f32 getSubAnimFrame() const { return 0.0f; }

    bool unk2;
    bool mIsNeedFullFaceAnim = false;
    bool mIsSubAnimOnlyAir = false;
};

}

class PlayerAnimator : public game::PlayerAnimator {
public:
    PlayerAnimator(PlayerModelHolder const*a,al::ActorDitherAnimator *b) : game::PlayerAnimator(a, b){}
};
