#pragma once

#include "Library/HostIO/HioNode.h"
#include "Library/Yaml/ByamlIter.h"

class PlayerConst : al::HioNode {
public:
    PlayerConst();
    PlayerConst(const al::ByamlIter&);

    virtual f32 getGravity() const;
    virtual f32 getFrictionAttack() const;
    virtual f32 getPushPower() const;
    virtual f32 getWaitPoseDegreeMax() const;
    virtual f32 getHillPoseDegreeMax() const;
    virtual f32 getTiltPoseDegreeMax() const;
    virtual f32 getSlerpQuatRate() const;
    virtual f32 getSlerpQuatRateWait() const;
    virtual f32 getSlerpQuatGrav() const;
    virtual s32 getPreInputFrameCapThrow() const;
    virtual s32 getEnableActionFrameCapCatch() const;
    virtual f32 getJumpPowerCapCatch() const;
    virtual f32 getJumpGravityCapCatch() const;
    virtual s32 getRunTimeContinuousThrow() const;
    virtual f32 getRunSpeedMaxContinuousThrow() const;
    virtual s32 getRunAccelFrameContinuousThrow() const;
    virtual f32 getSeparateCheckHeight() const;
    virtual f32 getSeparateOffsetLerpRate() const;
    virtual f32 getSeparateEnableThrowHeight() const;
    virtual f32 getTall() const;
    virtual f32 getCollisionRadius() const;
    virtual f32 getCollisionRadiusSquat() const;
    virtual f32 getCollisionRadiusStand() const;
    virtual f32 getCollisionSmallStepHeight() const;
    virtual f32 getCollisionResetLimit() const;
    virtual f32 getReflectCeilingPower() const;
    virtual f32 getReflectTossPower() const;
    virtual f32 getReflectUpperPunchScaleH() const;
    virtual f32 getCollisionHitDownAngleH() const;
    virtual f32 getCollisionHitDownEscapeAngleV() const;
    virtual f32 getShadowDropHeightScale() const;
    virtual f32 getShadowDropNormalAdd() const;
    virtual f32 getShadowDropLengthMin() const;
    virtual f32 getShadowDropLengthMax() const;
    virtual f32 getShadowDropLengthExtend() const;
    virtual f32 getGravityDamage() const;
    virtual f32 getHopPowerDamage() const;
    virtual f32 getPushPowerDamage() const;
    virtual s32 getDamageCancelFrame() const;
    virtual s32 getDamageInvalidCount() const;
    virtual s32 getDamageInvalidCountRecovery() const;
    virtual s32 getDamageInvalidCountAbyss() const;
    virtual f32 getNormalMinSpeed2D() const;
    virtual f32 getNormalMaxSpeed2D() const;
    virtual f32 getDashMaxSpeed2D() const;
    virtual s32 getNormalAccelFrame2D() const;
    virtual s32 getDashAccelFrame2D() const;
    virtual s32 getNormalDashAnimFrame2D() const;
    virtual s32 getNormalBrakeFrame2D() const;
    virtual s32 getStickOnBrakeFrame2D() const;
    virtual s32 getBrakeTurnStartFrame2D() const;
    virtual f32 getTurnEndSpeedRate2D() const;
    virtual f32 getJumpPowerMin2DArea() const;
    virtual f32 getJumpPowerMax2DArea() const;
    virtual f32 getJumpPowerMinBorder2D() const;
    virtual f32 getJumpPowerMaxBorder2D() const;
    virtual f32 getGravityMove() const;
    virtual f32 getNormalMaxSpeed() const;
    virtual f32 getNormalMinSpeed() const;
    virtual s32 getNormalAccelFrame() const;
    virtual f32 getRunAccelAverageScale() const;
    virtual s32 getNormalBrakeFrame() const;
    virtual f32 getDashJudgeSpeed() const;
    virtual s32 getStickOnBrakeFrame() const;
    virtual s32 getNormalDashAnimFrame() const;
    virtual f32 getRunAfterTurnSpeedMax() const;
    virtual f32 getRunAfterTurnScale() const;
    virtual s32 getRunAfterTurnFrame() const;
    virtual s32 getBrakeTurnStartFrame() const;
    virtual f32 getBrakeOnSpeedRate() const;
    virtual s32 getBrakeOnCounterBorder() const;
    virtual s32 getWallPushFrame() const;
    virtual s32 getRunDeepDownFrame() const;
    virtual s32 getRunDeepDownMargine() const;
    virtual s32 getQuickTurnJumpFrame() const;
    virtual s32 getRoundAccelFrame() const;
    virtual s32 getRoundBrakeFrame() const;
    virtual f32 getRoundFastDegree() const;
    virtual s32 getRoundAccelFrameFast() const;
    virtual f32 getRoundMinDegree() const;
    virtual s32 getRoundBrakeFrameForce() const;
    virtual f32 getRoundFastDegreeForce() const;
    virtual f32 getRoundLimitDegreeForce() const;
    virtual f32 getRoundLimitDegreeForceFast() const;
    virtual s32 getRoundAccelFrameForceFast() const;
    virtual f32 getRoundLimitDegreeMin() const;
    virtual f32 getRoundLimitDegree() const;
    virtual s32 getIceAccelFrame() const;
    virtual s32 getIceBrakeFrame() const;
    virtual s32 getIceBrakeFrameHigh() const;
    virtual s32 getIceBrakeFrameWall() const;
    virtual s32 getIceRoundAccelFrame() const;
    virtual s32 getIceRoundAccelFrameFast() const;
    virtual s32 getIceRoundBrakeFrame() const;
    virtual f32 getIceRoundFastDegree() const;
    virtual f32 getIceRoundMinDegree() const;
    virtual f32 getIceRoundLimitDegree() const;
    virtual f32 getHillAddSpeed() const;
    virtual f32 getHillSubSpeed() const;
    virtual s32 getHillAccelAddFrame() const;
    virtual s32 getHillAccelSubFrame() const;
    virtual f32 getHillAccelSubAngleMin() const;
    virtual f32 getHillAccelSubAngleMax() const;
    virtual f32 getStandAngleMin() const;
    virtual f32 getStandAngleMax() const;
    virtual f32 getHillAngleSpeedMin() const;
    virtual f32 getHillAngleSpeedMax() const;
    virtual s32 getSpinCapThrowFrame() const;
    virtual s32 getSpinCapThrowFrameAir() const;
    virtual s32 getSpinCapThrowFrameSwim() const;
    virtual s32 getSpinCapThrowFrameSwing() const;
    virtual s32 getSpinCapThrowFrameContinuous() const;
    virtual s32 getSpinAttackFrame() const;
    virtual s32 getSpinBrakeFrame() const;
    virtual f32 getSpinAirJumpPower() const;
    virtual f32 getSpinAirSpeedMax() const;
    virtual f32 getGravitySpinAir() const;
    virtual f32 getSlerpQuatRateSpinAir() const;
    virtual f32 getSpinBrakeRate() const;
    virtual f32 getSpinBrakeSideAccel() const;
    virtual f32 getSpinBrakeSideBrakeRate() const;
    virtual f32 getSpinBrakeSideMaxSpeedRate() const;
    virtual f32 getSpinRoundLimitDegree() const;
    virtual f32 getDamageFireJumpPower1st() const;
    virtual f32 getDamageFireJumpPower2nd() const;
    virtual f32 getDamageFireJumpMoveSpeed() const;
    virtual f32 getDamageFireCeilHitSpeed() const;
    virtual f32 getDamageFireGravity() const;
    virtual s32 getDamageFireNoGravityFrame() const;
    virtual s32 getDamageFireRunTime() const;
    virtual f32 getDamageFireRunSpeed() const;
    virtual f32 getDamageFireRunBrakeFrame() const;
    virtual s32 getSandSinkDeadTime() const;
    virtual s32 getSandSinkBrakeHeightH() const;
    virtual s32 getSandSinkBrakeHeightV() const;
    virtual f32 getSandSinkHeight() const;
    virtual f32 getSandSinkCapThrow() const;
    virtual f32 getSandSinkBrakeMinH() const;
    virtual f32 getSandSinkBrakeMaxH() const;
    virtual f32 getSandSinkBrakeMinV() const;
    virtual f32 getSandSinkBrakeMaxV() const;
    virtual f32 getSlopeSlideAngleStart() const;
    virtual f32 getSlopeSlideAngleEnd() const;
    virtual f32 getSlopeSlideAccel() const;
    virtual f32 getSlopeSlideBrake() const;
    virtual f32 getSlopeSlideMaxSpeed() const;
    virtual f32 getSlopeSlideSpeedEnd() const;
    virtual f32 getSlopeSlideSideAccel() const;
    virtual f32 getSlopeSlideSideBrake() const;
    virtual f32 getSlopeSlideSideMaxSpeed() const;
    virtual f32 getSlopeTurnDegree() const;
    virtual s32 getSlideInvalidFrame() const;
    virtual s32 getSlopeForceFrame() const;
    virtual f32 getSlopeSlideForceSideAccel() const;
    virtual f32 getSlopeSlideForceSideBrake() const;
    virtual f32 getSlopeSlideForceSideMaxSpeed() const;
    virtual f32 getSlopeSlideForceTurnDegree() const;
    virtual f32 getSlopeRollingSpeedStart() const;
    virtual f32 getSlopeRollingSpeedBoost() const;
    virtual f32 getSlopeRollingMaxSpeed() const;
    virtual s32 getSlopeRollingFrameMinBoost() const;
    virtual s32 getSlopeRollingFrameMin() const;
    virtual f32 getSlopeRollingStartJumpPower() const;
    virtual f32 getSlopeRollingStartSlideSpeed() const;
    virtual f32 getSlopeRollingAccel() const;
    virtual f32 getSlopeRollingBrake() const;
    virtual f32 getSlopeRollingAgainst() const;
    virtual f32 getSlopeRollingAnglePowerMax() const;
    virtual f32 getSlopeRollingSpeedEnd() const;
    virtual f32 getSlopeRollingSideAccel() const;
    virtual f32 getSlopeRollingSideBrake() const;
    virtual f32 getSlopeRollingSideMaxSpeed() const;
    virtual s32 getSlopeRollingUnRollFrame() const;
    virtual f32 getSlopeRollingEndBrake() const;
    virtual f32 getSlopeRollingEndBrakeEndSpeed() const;
    virtual f32 getSlopeRollingReStartAccel() const;
    virtual f32 getSlopeRollingReStartMaxAdd() const;
    virtual s32 getSlopeRollingReStartInterval() const;
    virtual s32 getSlopeRollingReStartSwing() const;
    virtual s32 getSlopeRollingReStartCharge() const;
    virtual s32 getSlopeRollingReStartForce() const;
    virtual f32 getSlopeRollingAccelOnSkate() const;
    virtual f32 getSlopeRollingSideAccelOnSkate() const;
    virtual f32 getSlopeRollingBrakeOnSkate() const;
    virtual s32 getExtendFrame() const;
    virtual f32 getJumpInertiaRate() const;
    virtual f32 getJumpPowerMin() const;
    virtual f32 getJumpPowerMax() const;
    virtual f32 getJumpGravity() const;
    virtual f32 getJumpBaseSpeedMax() const;
    virtual f32 getJumpMoveSpeedMin() const;
    virtual f32 getJumpMoveSpeedMax() const;
    virtual f32 getJumpAccelFront() const;
    virtual f32 getJumpAccelBack() const;
    virtual f32 getJumpAccelTurn() const;
    virtual f32 getJumpTurnAngleStart() const;
    virtual f32 getJumpTurnAngleLimit() const;
    virtual f32 getJumpTurnAngleFast() const;
    virtual f32 getJumpTurnAngleFastLimit() const;
    virtual s32 getJumpTurnAccelFrame() const;
    virtual s32 getJumpTurnAccelFrameFast() const;
    virtual s32 getJumpTurnBrakeFrame() const;
    virtual f32 getTrampleGravity() const;
    virtual f32 getTrampleJumpPower() const;
    virtual f32 getTrampleHighGravity() const;
    virtual f32 getTrampleHighJumpPower() const;
    virtual f32 getTrampleGravity2D() const;
    virtual f32 getTrampleJumpPower2D() const;
    virtual f32 getTrampleHighGravity2D() const;
    virtual f32 getTrampleHighJumpPower2D() const;
    virtual f32 getTrampleHipDropGravity() const;
    virtual f32 getTrampleHipDropJumpPower() const;
    virtual f32 getTrampleRisingBrakeVelH() const;
    virtual f32 getTrampleJumpCodePower() const;
    virtual f32 getTrampleJumpCodePowerSmall() const;
    virtual f32 getCapLeapFrogJumpGravity() const;
    virtual f32 getCapLeapFrogJumpPower() const;
    virtual f32 getCapLeapFrogJumpPowerAir() const;
    virtual f32 getObjLeapFrogJumpPower() const;
    virtual f32 getObjLeapFrogJumpPowerHigh() const;
    virtual f32 getCapHeadSpringJumpGravity() const;
    virtual f32 getCapHeadSpringJumpPower() const;
    virtual f32 getCapHeadSpringJumpGravityHigh() const;
    virtual f32 getCapHeadSpringJumpPowerHigh() const;
    virtual f32 getCapHeadSpringSpeedMax() const;
    virtual s32 getContinuousJumpPreInputFrame() const;
    virtual s32 getContinuousJumpCount() const;
    virtual s32 getContinuousJumpTimer() const;
    virtual f32 getContinuousJumpPowerMin() const;
    virtual f32 getJumpPowerMax2nd() const;
    virtual f32 getJumpGravity2nd() const;
    virtual f32 getJumpPowerMax3rd() const;
    virtual f32 getJumpGravity3rd() const;
    virtual f32 getSpinFlowerJumpGravity() const;
    virtual f32 getSpinFlowerJumpFallSpeedMax() const;
    virtual f32 getSpinFlowerJumpMovePower() const;
    virtual f32 getSpinFlowerJumpVelMax() const;
    virtual s32 getSpinFlowerJumpStayFrame() const;
    virtual f32 getSpinFlowerJumpStaySpeedMax() const;
    virtual f32 getSpinFlowerJumpNoInputBrake() const;
    virtual f32 getSpinFlowerJumpDownFallInitSpeed() const;
    virtual f32 getSpinFlowerJumpDownFallPower() const;
    virtual f32 getSpinFlowerJumpDownFallSpeedMax() const;
    virtual f32 getJumpGravityForceRun() const;
    virtual f32 getJumpPowerForceRun() const;
    virtual f32 getCapCatchPopPower() const;
    virtual f32 getCapCatchPopGravity() const;
    virtual f32 getSquatJumpGravity() const;
    virtual f32 getSquatJumpPower() const;
    virtual f32 getSquatJumpBackPower() const;
    virtual f32 getSquatJumpMovePowerFront() const;
    virtual f32 getSquatJumpMovePowerSide() const;
    virtual f32 getSquatJumpMoveSpeedMax() const;
    virtual f32 getTurnJumpGravity() const;
    virtual f32 getTurnJumpPower() const;
    virtual f32 getTurnJumpVelH() const;
    virtual f32 getTurnJumpBrake() const;
    virtual f32 getTurnJumpAccel() const;
    virtual f32 getTurnJumpSideAccel() const;
    virtual f32 getLongJumpAccel() const;
    virtual f32 getLongJumpBrake() const;
    virtual f32 getLongJumpSideAccel() const;
    virtual f32 getLongJumpGravity() const;
    virtual f32 getLongJumpJumpPow() const;
    virtual f32 getLongJumpMovePow() const;
    virtual f32 getLongJumpInitSpeed() const;
    virtual f32 getLongJumpSpeed() const;
    virtual f32 getLongJumpSpeedMin() const;
    virtual s32 getContinuousLongJumpCount() const;
    virtual s32 getContinuousLongJumpTimer() const;
    virtual f32 getGravityAir() const;
    virtual f32 getFrictionAir() const;
    virtual f32 getFallSpeedMax() const;
    virtual f32 getLongFallDistance() const;
    virtual f32 getFallWallScaleVelocity() const;
    virtual s32 getDownFallFrameMin() const;
    virtual f32 getGravityWallSlide() const;
    virtual f32 getWallHeightLowLimit() const;
    virtual f32 getWallKeepDegree() const;
    virtual s32 getWallKeepFrame() const;
    virtual f32 getWallJumpGravity() const;
    virtual f32 getWallJumpHSpeed() const;
    virtual f32 getWallJumpPower() const;
    virtual s32 getWallJumpInvalidateInputFrame() const;
    virtual s32 getWallInhibitAfterPunch() const;
    virtual f32 getWallFollowAngleH() const;
    virtual f32 getWallFollowAngleV() const;
    virtual f32 getWallCatchDegree() const;
    virtual f32 getWallCatchHeightEdgeTop() const;
    virtual f32 getWallCatchHeightBottom() const;
    virtual f32 getWallCatchKeepDegree() const;
    virtual f32 getWallCatchMoveDegree() const;
    virtual f32 getWallCatchMoveSpeed() const;
    virtual f32 getWallCatchMoveHeightRange() const;
    virtual s32 getWallCatchMoveInterpolate() const;
    virtual s32 getWallCatchMoveFrame() const;
    virtual s32 getWallCatchMoveFrameFast() const;
    virtual s32 getWallCatchMoveFrameSwing() const;
    virtual f32 getWallCatchInputRepeatAngle() const;
    virtual f32 getWallClimbDegree() const;
    virtual s32 getWallClimbJumpStartFrame() const;
    virtual s32 getWallClimbJumpEndFrame() const;
    virtual s32 getWallClimbStartFrame() const;
    virtual f32 getWallClimbGravity() const;
    virtual f32 getWallFallJumpSpeed() const;
    virtual f32 getWallClimbJumpSpeedV() const;
    virtual f32 getWallClimbJumpSpeedH() const;
    virtual f32 getWallClimbJumpGravity() const;
    virtual s32 getWallClimbJumpInvalidFrame() const;
    virtual f32 getWallCatchHipLocalOffset() const;
    virtual f32 getWallCatchHipStability() const;
    virtual f32 getWallCatchHipFriction() const;
    virtual f32 getWallCatchHipLimitDegree() const;
    virtual f32 getWallCatchStainAreaOffset() const;
    virtual f32 getGrabCeilRange() const;
    virtual f32 getGrabCeilBodyRadius() const;
    virtual f32 getGrabCeilLeaveSpeedMin() const;
    virtual f32 getGrabCeilLeavePopPower() const;
    virtual f32 getGrabCeilLeavePopGravity() const;
    virtual f32 getGrabCeilSwingStartOffset() const;
    virtual f32 getGrabCeilReverseInputBorder() const;
    virtual f32 getGrabCeilInputPowerBorder() const;
    virtual f32 getGrabCeilSwingWaitEnergy() const;
    virtual f32 getGrabCeilEnableJumpEnergy() const;
    virtual f32 getGrabCeilEnableJumpEnergyMax() const;
    virtual f32 getGrabCeilJumpForceAngle() const;
    virtual f32 getGrabCeilJumpPower() const;
    virtual f32 getGrabCeilJumpMoveMin() const;
    virtual f32 getGrabCeilJumpMoveMax() const;
    virtual f32 getGrabCeilJumpGravity() const;
    virtual s32 getGrabCeilJumpInvalidFrame() const;
    virtual s32 getGrabCeilEnableNextFrame() const;
    virtual s32 getGrabCeilEnableFallSnapFrame() const;
    virtual s32 getPoleClimbPreInputSwing() const;
    virtual f32 getPoleClimbInputRepeatAngle() const;
    virtual f32 getPoleClimbInputDegreeMove() const;
    virtual f32 getPoleClimbCatchRange() const;
    virtual f32 getPoleClimbCatchRangeMin() const;
    virtual f32 getPoleClimbCatchRangeMax() const;
    virtual f32 getPoleClimbJointAngleMin() const;
    virtual f32 getPoleClimbJointAngleMax() const;
    virtual f32 getPoleClimbJointRangeMin() const;
    virtual f32 getPoleClimbJointRangeMax() const;
    virtual f32 getPoleClimbMoveWallDegree() const;
    virtual f32 getPoleClimbUpMargine() const;
    virtual f32 getPoleClimbUpSpeed() const;
    virtual s32 getPoleClimbUpFrame() const;
    virtual s32 getPoleClimbUpFrameFast() const;
    virtual s32 getPoleClimbUpFrameSwing() const;
    virtual f32 getPoleClimbDownSpeed() const;
    virtual f32 getPoleClimbDownSpeedFast() const;
    virtual f32 getPoleClimbDownSpeedSwing() const;
    virtual s32 getPoleClimbDownFrame() const;
    virtual s32 getPoleClimbDownKeepTime() const;
    virtual f32 getPoleClimbTurnDist() const;
    virtual s32 getPoleClimbTurnFrame() const;
    virtual s32 getPoleClimbTurnStopFrame() const;
    virtual s32 getPoleTopStartFrame() const;
    virtual s32 getPoleTopEndFrame() const;
    virtual f32 getPoleTopTurnSpeed() const;
    virtual f32 getPoleTopEndUnderOffsetY() const;
    virtual s32 getGroundSpinFrame() const;
    virtual f32 getGroundSpinMoveSpeedMax() const;
    virtual f32 getGroundSpinAccelRate() const;
    virtual f32 getGroundSpinBrakeRate() const;
    virtual f32 getSpinJumpGravity() const;
    virtual f32 getSpinJumpPower() const;
    virtual f32 getSpinJumpMoveSpeedMax() const;
    virtual f32 getSpinJumpDownFallInitSpeed() const;
    virtual f32 getSpinJumpDownFallPower() const;
    virtual f32 getSpinJumpDownFallSpeedMax() const;
    virtual f32 getSquatBrakeEndSpeed() const;
    virtual f32 getSquatAccelRate() const;
    virtual f32 getSquatBrakeRate() const;
    virtual f32 getSquatBrakeRateOnSkate() const;
    virtual f32 getSquatBrakeSideAccel() const;
    virtual f32 getSquatBrakeSideRate() const;
    virtual f32 getSquatBrakeSideAccelOnSkate() const;
    virtual f32 getSquatBrakeSideRateOnSkate() const;
    virtual f32 getSquatBrakeSideMaxSpeedRate() const;
    virtual f32 getSquatWalkSpeed() const;
    virtual f32 getSquatWalkTurnSpeed() const;
    virtual s32 getSquatWalkTurnFrame() const;
    virtual f32 getSquatJumpCeilSlideSpeed2D() const;
    virtual f32 getHipDropSpeed() const;
    virtual f32 getHipDropGravity() const;
    virtual f32 getHipDropSpeedMax() const;
    virtual s32 getHipDropLandCancelFrame() const;
    virtual f32 getHipDropHeight() const;
    virtual s32 getHipDropMsgInterval() const;
    virtual f32 getJumpHipDropPower() const;
    virtual s32 getJumpHipDropPermitBeginFrame() const;
    virtual s32 getJumpHipDropPermitEndFrame() const;
    virtual f32 getHeadSlidingSpeed() const;
    virtual f32 getHeadSlidingSpeedMin() const;
    virtual f32 getHeadSlidingBrake() const;
    virtual f32 getHeadSlidingSideAccel() const;
    virtual f32 getHeadSlidingJump() const;
    virtual f32 getHeadSlidingGravityAir() const;
    virtual f32 getSwimCenterOffset() const;
    virtual f32 getSwimWallCatchOffset() const;
    virtual f32 getSwimRisePower() const;
    virtual f32 getSwimRiseSpeedMax() const;
    virtual s32 getSwimRiseFrame() const;
    virtual f32 getSwimGravity() const;
    virtual f32 getSwimGravityWalk() const;
    virtual f32 getSwimFallSpeedMax() const;
    virtual f32 getSwimFloorAccelH() const;
    virtual f32 getSwimFloorSpeedMaxH() const;
    virtual f32 getSwimHighAccelH() const;
    virtual f32 getSwimHighSpeedMaxH() const;
    virtual f32 getSwimLowAccelH() const;
    virtual f32 getSwimLowSpeedMaxH() const;
    virtual f32 getSwimBrakeRateH() const;
    virtual f32 getSwimWallHitSpeedMinH() const;
    virtual s32 getSwimHighAccelPermitFrame() const;
    virtual f32 getSwimFlowFieldBlend() const;
    virtual f32 getSwimWalkAnimMinRate() const;
    virtual f32 getSwimWalkAnimMaxRate() const;
    virtual f32 getSwimWalkMaxSpeed() const;
    virtual f32 getSwimSpinCapUpPower() const;
    virtual f32 getSwimSpinCapUpSpeedMax() const;
    virtual f32 getSwimRotStartAngle() const;
    virtual f32 getSwimRotFastAngle() const;
    virtual s32 getSwimRotAccelFrame() const;
    virtual s32 getSwimRotAccelFrameFast() const;
    virtual s32 getSwimRotBrakeFrame() const;
    virtual f32 getSwimRotSpeedChangeStart() const;
    virtual f32 getSwimRotSpeedForward() const;
    virtual f32 getSwimRotSpeedMax() const;
    virtual f32 getSwimSurfaceAccelH() const;
    virtual f32 getSwimSurfaceSpeedMaxH() const;
    virtual s32 getSwimSurfaceSpinCapFrame() const;
    virtual f32 getSwimSurfaceSpinCapSpeedMaxH() const;
    virtual f32 getSwimSurfaceStartDist() const;
    virtual f32 getSwimSurfaceEndDist() const;
    virtual f32 getSwimSurfaceGravity() const;
    virtual f32 getSwimSurfaceBaseHeight() const;
    virtual f32 getSwimSurfaceSpring() const;
    virtual f32 getSwimSurfaceDamper() const;
    virtual s32 getSwimSurfaceDamperStart() const;
    virtual s32 getSwimSurfaceDamperFrame() const;
    virtual f32 getSwimSurfaceEnableJumpHeight() const;
    virtual s32 getSwimSurfacePreInputJumpFrame() const;
    virtual f32 getSwimSurfaceMoveSpring() const;
    virtual f32 getSwimSurfaceMoveDamper() const;
    virtual f32 getSwimSurfaceMoveBaseHeight() const;
    virtual f32 getSwimRunSurfaceBaseHeight() const;
    virtual f32 getSwimRunSurfaceApproachRate() const;
    virtual f32 getSwimRunSurfaceApproachLimit() const;
    virtual f32 getSwimRunSurfaceBrakeBorder() const;
    virtual f32 getSwimRunSurfaceBrakeH() const;
    virtual f32 getSwimRunSurfaceApproachBorderMax() const;
    virtual f32 getSwimRunSurfaceApproachBorderMin() const;
    virtual f32 getSwimRunSurfaceApproachRateMin() const;
    virtual f32 getSwimFallInSpeed() const;
    virtual f32 getSwimFallInBrakeH() const;
    virtual f32 getSwimFallInBrakeV() const;
    virtual f32 getSwimHeadInBrakeH() const;
    virtual f32 getSwimHeadInBrakeV() const;
    virtual f32 getSwimHeadInRisePower() const;
    virtual f32 getSwimHeadInRiseSpeedMax() const;
    virtual f32 getSwimHeadInSurfaceHeight() const;
    virtual s32 getSwimFallInForceSurfaceFrame() const;
    virtual s32 getSwimFallInvalidJumpFrame() const;
    virtual f32 getSwimDiveStartSpeed() const;
    virtual f32 getSwimDiveBrake() const;
    virtual f32 getSwimDiveEndSpeed() const;
    virtual s32 getSwimDiveLandCount() const;
    virtual s32 getSwimDiveLandCancelFrame() const;
    virtual s32 getSwimDiveNoBrakeFrame() const;
    virtual s32 getSwimDiveButtonValidFrame() const;
    virtual s32 getSwimDiveEndFrame() const;
    virtual f32 getSwimDiveInBrakeH() const;
    virtual f32 getSwimDiveInBrakeV() const;
    virtual f32 getSwimDiveInRisePower() const;
    virtual f32 getSwimDiveInRiseSpeedMax() const;
    virtual f32 getSwimDiveInSurfaceHeight() const;
    virtual s32 getSwimDiveInKeepFrame() const;
    virtual s32 getSwimHeadSlidingFrame() const;
    virtual s32 getSwimHeadSlidingBrakeFrame() const;
    virtual f32 getSwimHeadSlidingSpeed() const;
    virtual f32 getSwimHeadSlidingSpeedEnd() const;
    virtual f32 getSwimHeadSlidingBrake() const;
    virtual f32 getSwimHeadSlidingSideAccel() const;
    virtual f32 getSwimHeadSlidingJump() const;
    virtual f32 getSwimHeadSlidingGravity() const;
    virtual s32 getSwimHeadSlidingEndBrakeFrame() const;
    virtual s32 getSwimHeadSlidingEndSpeedMin() const;
    virtual f32 getSwimJumpHipDropSpeed() const;
    virtual f32 getSwimJumpHipDropBrakeV() const;
    virtual f32 getSwimJumpHipDropBrakeVCeiling() const;
    virtual f32 getSwimJumpHipDropGravity() const;
    virtual f32 getSwimJumpHipDropCancelSpeed() const;
    virtual f32 getSwimJumpHipDropAccelH() const;
    virtual f32 getSwimJumpHipDropMoveSpeedH() const;
    virtual f32 getSwimJumpHipDropPopSpeed() const;
    virtual f32 getSwimJumpHipDropPopJumpAdd() const;
    virtual f32 getSwimTramplePower() const;
    virtual f32 getDiveTramplePower() const;
    virtual s32 getDiveTrampleCancelFrame() const;
    virtual f32 getDamageSwimPushPower() const;
    virtual f32 getDamageSwimGravity() const;
    virtual s32 getDamageSwimCancelFrame() const;
    virtual f32 getDamageSwimSurfaceGravity() const;
    virtual f32 getDamageSwimSurfaceHopPower() const;
    virtual f32 getDamageSwimSurfacePushPower() const;
    virtual f32 getDamageSwimSurfaceLandSpeed() const;
    virtual f32 getDamageSwimSurfaceLandBrake() const;
    virtual f32 getDamageSwimSurfaceLandEndSpeed() const;
    virtual s32 getDamageSwimSurfaceCancelFrame() const;
    virtual f32 getDamageSwimBrakeRateGround() const;
    virtual s32 getOxygenReduceFrame() const;
    virtual s32 getOxygenNoReduceFrame() const;
    virtual s32 getOxygenRecoveryFrame() const;
    virtual s32 getOxygenDamageInterval() const;
    virtual s32 getIceWaterDamageInterval() const;
    virtual s32 getIceWaterRecoveryFrame() const;
    virtual f32 getMoveAnimSpeedMax() const;
    virtual f32 getAnimFrameRateSpeedMin() const;
    virtual f32 getRunBorderSpeed() const;
    virtual f32 getRunBlendRange() const;
    virtual f32 getDashBorderSpeed() const;
    virtual f32 getDashBlendRange() const;
    virtual f32 getDashFastBorderSpeed() const;
    virtual f32 getDashFastBlendRange() const;
    virtual f32 getAnimFrameRateSpeedMax() const;
    virtual f32 getAnimFrameRateRunStart() const;
    virtual f32 getAnimFrameRateMinRun() const;
    virtual f32 getAnimFrameRateMaxRun() const;
    virtual f32 getAnimFrameRateMaxDash() const;
    virtual f32 getAnimFrameRateMaxDashFast() const;
    virtual f32 getRunStartPlayFrameScale() const;
    virtual s32 getRunStartBlendFrame() const;
    virtual f32 getDamageFireRunAnimRate() const;
    virtual f32 getRunSkateAnimSpeedOffset() const;
    virtual f32 getAnimFrameRateRange2D() const;
    virtual f32 getAnimFrameRateMinRun2D() const;
    virtual f32 getAnimFrameRateMaxRun2D() const;
    virtual s32 getIKBlendFrameRun() const;
    virtual f32 getIKBlendRateRunMin() const;
    virtual f32 getIKBlendRateRunMax() const;
    virtual f32 getRollingAnimBorderSpeedMin() const;
    virtual f32 getRollingAnimBorderSpeedMax() const;
    virtual f32 getRollingAnimFrameRateMin() const;
    virtual f32 getRollingAnimFrameRateMax() const;
    virtual s32 getSwimPaddleAnimInterval() const;
    virtual s32 getSwimPaddleAnimRateIntervalMax() const;
    virtual s32 getSwimPaddleAnimRateIntervalMin() const;
    virtual f32 getSwimPaddleAnimMaxRate() const;
    virtual f32 getSwimBentForwardMax() const;
    virtual f32 getSwimBentForwardBlendRate() const;
    virtual f32 getSwimBentSideMax() const;
    virtual f32 getSwimBentSpineMax() const;
    virtual f32 getSwimBentSideBlendRate() const;
    virtual f32 getSwimBentFrontMax() const;
    virtual f32 getSwimBentFrontBlendRate() const;
    virtual f32 getSwimWalkAnimSpeedMax() const;
    virtual f32 getSwimWalkAnimSpeedMin() const;
    virtual f32 getSwimWalkAnimFrameRateMax() const;
    virtual f32 getSwimWalkAnimFrameRateMin() const;
    virtual f32 getSandSinkBorderMin() const;
    virtual f32 getSandSinkBorderMax() const;
    virtual f32 getSandSinkBorderRateMin() const;
    virtual f32 getSandSinkBorderRateMax() const;
    virtual f32 getSandSinkFrameRateMin() const;
    virtual f32 getSandSinkFrameRateMax() const;
    virtual s32 getLookAtEyeKeepFrame() const;
    virtual s32 getLookAtEyeKeepFrameInSight() const;
    virtual s32 getLookAtEyeKeepFrameWait() const;
    virtual f32 getLookAtEyeDistance() const;
    virtual f32 getLookAtEyeAngleMinH() const;
    virtual f32 getLookAtEyeAngleMinInSightH() const;
    virtual f32 getLookAtEyeAngleMaxH() const;
    virtual f32 getLookAtEyeAngleMinV() const;
    virtual f32 getLookAtEyeAngleMinInSightV() const;
    virtual f32 getLookAtEyeAngleMaxV() const;
    virtual f32 getTiltEyeBorderStart() const;
    virtual f32 getTiltEyeBorderEnd() const;
    virtual f32 getTiltEyeAngleScale() const;
    virtual f32 getCenterTiltRateMax() const;
    virtual f32 getNoseChildLocalOffset() const;
    virtual f32 getNoseStability() const;
    virtual f32 getNoseFriction() const;
    virtual f32 getNoseLimitDegree() const;
    virtual f32 getMustacheChildLocalOffset() const;
    virtual f32 getMustacheStability() const;
    virtual f32 getMustacheFriction() const;
    virtual f32 getMustacheLimitDegree() const;
    virtual s32 getCapInterpolateFrame() const;
    virtual f32 getCapChildLocalOffset() const;
    virtual f32 getCapStability() const;
    virtual f32 getCapFriction() const;
    virtual f32 getCapLimitDegree() const;
    virtual f32 getCapTransStability() const;
    virtual f32 getCapTransFriction() const;
    virtual f32 getCapTransLimit() const;
    virtual s32 getCapManHeroEyesWaitAppearFrame() const;
    virtual s32 getDeadWipeStartDamage() const;
    virtual s32 getDeadWipeWaitDamage() const;
    virtual s32 getDeadWipeStartAbyss() const;
    virtual s32 getDeadWipeWaitAbyss() const;
    virtual s32 getDeadWipeStartAbyssWithCapMsg() const;
    virtual s32 getDeadWipeWaitAbyssWithCapMsg() const;
    virtual s32 getDeadWipeStartPress() const;
    virtual s32 getDeadWipeWaitPress() const;
    virtual s32 getDeadWipeStartSandSink() const;
    virtual s32 getDeadWipeWaitSandSink() const;
    virtual s32 getDeadWipeStartNoOxygen() const;
    virtual s32 getDeadWipeWaitNoOxygen() const;
    virtual s32 getDeadWipeStartIceWater() const;
    virtual s32 getDeadWipeWaitIceWater() const;
    virtual f32 getCoinDashSpeed() const;
    virtual f32 getCoinDashSpeedLimit() const;
    virtual f32 getAdditionalSpeedLimit() const;

private:
    f32 mGravity;
    f32 mFrictionAttack;
    f32 mPushPower;
    f32 mWaitPoseDegreeMax;
    f32 mHillPoseDegreeMax;
    f32 mTiltPoseDegreeMax;
    f32 mSlerpQuatRate;
    f32 mSlerpQuatRateWait;
    f32 mSlerpQuatGrav;
    s32 mPreInputFrameCapThrow;
    s32 mEnableActionFrameCapCatch;
    f32 mJumpPowerCapCatch;
    f32 mJumpGravityCapCatch;
    s32 mRunTimeContinuousThrow;
    f32 mRunSpeedMaxContinuousThrow;
    s32 mRunAccelFrameContinuousThrow;
    f32 mSeparateCheckHeight;
    f32 mSeparateOffsetLerpRate;
    f32 mSeparateEnableThrowHeight;
    f32 mTall;
    f32 mCollisionRadius;
    f32 mCollisionRadiusSquat;
    f32 mCollisionRadiusStand;
    f32 mCollisionSmallStepHeight;
    f32 mCollisionResetLimit;
    f32 mReflectCeilingPower;
    f32 mReflectTossPower;
    f32 mReflectUpperPunchScaleH;
    f32 mCollisionHitDownAngleH;
    f32 mCollisionHitDownEscapeAngleV;
    f32 mShadowDropHeightScale;
    f32 mShadowDropNormalAdd;
    f32 mShadowDropLengthMin;
    f32 mShadowDropLengthMax;
    f32 mShadowDropLengthExtend;
    f32 mGravityDamage;
    f32 mHopPowerDamage;
    f32 mPushPowerDamage;
    s32 mDamageCancelFrame;
    s32 mDamageInvalidCount;
    s32 mDamageInvalidCountRecovery;
    s32 mDamageInvalidCountAbyss;
    f32 mNormalMinSpeed2D;
    f32 mNormalMaxSpeed2D;
    f32 mDashMaxSpeed2D;
    s32 mNormalAccelFrame2D;
    s32 mDashAccelFrame2D;
    s32 mNormalDashAnimFrame2D;
    s32 mNormalBrakeFrame2D;
    s32 mStickOnBrakeFrame2D;
    s32 mBrakeTurnStartFrame2D;
    f32 mTurnEndSpeedRate2D;
    f32 mJumpPowerMin2DArea;
    f32 mJumpPowerMax2DArea;
    f32 mJumpPowerMinBorder2D;
    f32 mJumpPowerMaxBorder2D;
    f32 mGravityMove;
    f32 mNormalMaxSpeed;
    f32 mNormalMinSpeed;
    s32 mNormalAccelFrame;
    f32 mRunAccelAverageScale;
    s32 mNormalBrakeFrame;
    f32 mDashJudgeSpeed;
    s32 mStickOnBrakeFrame;
    s32 mNormalDashAnimFrame;
    f32 mRunAfterTurnSpeedMax;
    f32 mRunAfterTurnScale;
    s32 mRunAfterTurnFrame;
    s32 mBrakeTurnStartFrame;
    f32 mBrakeOnSpeedRate;
    s32 mBrakeOnCounterBorder;
    s32 mWallPushFrame;
    s32 mRunDeepDownFrame;
    s32 mRunDeepDownMargine;
    s32 mQuickTurnJumpFrame;
    s32 mRoundAccelFrame;
    s32 mRoundBrakeFrame;
    f32 mRoundFastDegree;
    s32 mRoundAccelFrameFast;
    f32 mRoundMinDegree;
    s32 mRoundBrakeFrameForce;
    f32 mRoundFastDegreeForce;
    f32 mRoundLimitDegreeForce;
    f32 mRoundLimitDegreeForceFast;
    s32 mRoundAccelFrameForceFast;
    f32 mRoundLimitDegreeMin;
    f32 mRoundLimitDegree;
    s32 mIceAccelFrame;
    s32 mIceBrakeFrame;
    s32 mIceBrakeFrameHigh;
    s32 mIceBrakeFrameWall;
    s32 mIceRoundAccelFrame;
    s32 mIceRoundAccelFrameFast;
    s32 mIceRoundBrakeFrame;
    f32 mIceRoundFastDegree;
    f32 mIceRoundMinDegree;
    f32 mIceRoundLimitDegree;
    f32 mHillAddSpeed;
    f32 mHillSubSpeed;
    s32 mHillAccelAddFrame;
    s32 mHillAccelSubFrame;
    f32 mHillAccelSubAngleMin;
    f32 mHillAccelSubAngleMax;
    f32 mStandAngleMin;
    f32 mStandAngleMax;
    f32 mHillAngleSpeedMin;
    f32 mHillAngleSpeedMax;
    s32 mSpinCapThrowFrame;
    s32 mSpinCapThrowFrameAir;
    s32 mSpinCapThrowFrameSwim;
    s32 mSpinCapThrowFrameSwing;
    s32 mSpinCapThrowFrameContinuous;
    s32 mSpinAttackFrame;
    s32 mSpinBrakeFrame;
    f32 mSpinAirJumpPower;
    f32 mSpinAirSpeedMax;
    f32 mGravitySpinAir;
    f32 mSlerpQuatRateSpinAir;
    f32 mSpinBrakeRate;
    f32 mSpinBrakeSideAccel;
    f32 mSpinBrakeSideBrakeRate;
    f32 mSpinBrakeSideMaxSpeedRate;
    f32 mSpinRoundLimitDegree;
    f32 mDamageFireJumpPower1st;
    f32 mDamageFireJumpPower2nd;
    f32 mDamageFireJumpMoveSpeed;
    f32 mDamageFireCeilHitSpeed;
    f32 mDamageFireGravity;
    s32 mDamageFireNoGravityFrame;
    s32 mDamageFireRunTime;
    f32 mDamageFireRunSpeed;
    f32 mDamageFireRunBrakeFrame;
    s32 mSandSinkDeadTime;
    s32 mSandSinkBrakeHeightH;
    s32 mSandSinkBrakeHeightV;
    f32 mSandSinkHeight;
    f32 mSandSinkCapThrow;
    f32 mSandSinkBrakeMinH;
    f32 mSandSinkBrakeMaxH;
    f32 mSandSinkBrakeMinV;
    f32 mSandSinkBrakeMaxV;
    f32 mSlopeSlideAngleStart;
    f32 mSlopeSlideAngleEnd;
    f32 mSlopeSlideAccel;
    f32 mSlopeSlideBrake;
    f32 mSlopeSlideMaxSpeed;
    f32 mSlopeSlideSpeedEnd;
    f32 mSlopeSlideSideAccel;
    f32 mSlopeSlideSideBrake;
    f32 mSlopeSlideSideMaxSpeed;
    f32 mSlopeTurnDegree;
    s32 mSlideInvalidFrame;
    s32 mSlopeForceFrame;
    f32 mSlopeSlideForceSideAccel;
    f32 mSlopeSlideForceSideBrake;
    f32 mSlopeSlideForceSideMaxSpeed;
    f32 mSlopeSlideForceTurnDegree;
    f32 mSlopeRollingSpeedStart;
    f32 mSlopeRollingSpeedBoost;
    f32 mSlopeRollingMaxSpeed;
    s32 mSlopeRollingFrameMinBoost;
    s32 mSlopeRollingFrameMin;
    f32 mSlopeRollingStartJumpPower;
    f32 mSlopeRollingStartSlideSpeed;
    f32 mSlopeRollingAccel;
    f32 mSlopeRollingBrake;
    f32 mSlopeRollingAgainst;
    f32 mSlopeRollingAnglePowerMax;
    f32 mSlopeRollingSpeedEnd;
    f32 mSlopeRollingSideAccel;
    f32 mSlopeRollingSideBrake;
    f32 mSlopeRollingSideMaxSpeed;
    s32 mSlopeRollingUnRollFrame;
    f32 mSlopeRollingEndBrake;
    f32 mSlopeRollingEndBrakeEndSpeed;
    f32 mSlopeRollingReStartAccel;
    f32 mSlopeRollingReStartMaxAdd;
    s32 mSlopeRollingReStartinterval;
    s32 mSlopeRollingReStartSwing;
    s32 mSlopeRollingReStartCharge;
    s32 mSlopeRollingReStartForce;
    f32 mSlopeRollingAccelOnSkate;
    f32 mSlopeRollingSideAccelOnSkate;
    f32 mSlopeRollingBrakeOnSkate;
    s32 mExtendFrame;
    f32 mJumpInertiaRate;
    f32 mJumpPowerMin;
    f32 mJumpPowerMax;
    f32 mJumpGravity;
    f32 mJumpBaseSpeedMax;
    f32 mJumpMoveSpeedMin;
    f32 mJumpMoveSpeedMax;
    f32 mJumpAccelFront;
    f32 mJumpAccelBack;
    f32 mJumpAccelTurn;
    f32 mJumpTurnAngleStart;
    f32 mJumpTurnAngleLimit;
    f32 mJumpTurnAngleFast;
    f32 mJumpTurnAngleFastLimit;
    s32 mJumpTurnAccelFrame;
    s32 mJumpTurnAccelFrameFast;
    s32 mJumpTurnBrakeFrame;
    f32 mTrampleGravity;
    f32 mTrampleJumpPower;
    f32 mTrampleHighGravity;
    f32 mTrampleHighJumpPower;
    f32 mTrampleGravity2D;
    f32 mTrampleJumpPower2D;
    f32 mTrampleHighGravity2D;
    f32 mTrampleHighJumpPower2D;
    f32 mTrampleHipDropGravity;
    f32 mTrampleHipDropJumpPower;
    f32 mTrampleRisingBrakeVelH;
    f32 mTrampleJumpCodePower;
    f32 mTrampleJumpCodePowerSmall;
    f32 mCapLeapFrogJumpGravity;
    f32 mCapLeapFrogJumpPower;
    f32 mCapLeapFrogJumpPowerAir;
    f32 mObjLeapFrogJumpPower;
    f32 mObjLeapFrogJumpPowerHigh;
    f32 mCapHeadSpringJumpGravity;
    f32 mCapHeadSpringJumpPower;
    f32 mCapHeadSpringJumpGravityHigh;
    f32 mCapHeadSpringJumpPowerHigh;
    f32 mCapHeadSpringSpeedMax;
    s32 mContinuousJumpPreInputFrame;
    s32 mContinuousJumpCount;
    s32 mContinuousJumpTimer;
    f32 mContinuousJumpPowerMin;
    f32 mJumpPowerMax2nd;
    f32 mJumpGravity2nd;
    f32 mJumpPowerMax3rd;
    f32 mJumpGravity3rd;
    f32 mSpinFlowerJumpGravity;
    f32 mSpinFlowerJumpFallSpeedMax;
    f32 mSpinFlowerJumpMovePower;
    f32 mSpinFlowerJumpVelMax;
    s32 mSpinFlowerJumpStayFrame;
    f32 mSpinFlowerJumpStaySpeedMax;
    f32 mSpinFlowerJumpNoInputBrake;
    f32 mSpinFlowerJumpDownFallInitSpeed;
    f32 mSpinFlowerJumpDownFallPower;
    f32 mSpinFlowerJumpDownFallSpeedMax;
    f32 mJumpGravityForceRun;
    f32 mJumpPowerForceRun;
    f32 mCapCatchPopPower;
    f32 mCapCatchPopGravity;
    f32 mSquatJumpGravity;
    f32 mSquatJumpPower;
    f32 mSquatJumpBackPower;
    f32 mSquatJumpMovePowerFront;
    f32 mSquatJumpMovePowerSide;
    f32 mSquatJumpMoveSpeedMax;
    f32 mTurnJumpGravity;
    f32 mTurnJumpPower;
    f32 mTurnJumpVelH;
    f32 mTurnJumpBrake;
    f32 mTurnJumpAccel;
    f32 mTurnJumpSideAccel;
    f32 mLongJumpAccel;
    f32 mLongJumpBrake;
    f32 mLongJumpSideAccel;
    f32 mLongJumpGravity;
    f32 mLongJumpJumpPow;
    f32 mLongJumpMovePow;
    f32 mLongJumpInitSpeed;
    f32 mLongJumpSpeed;
    f32 mLongJumpSpeedMin;
    s32 mContinuousLongJumpCount;
    s32 mContinuousLongJumpTimer;
    f32 mGravityAir;
    f32 mFrictionAir;
    f32 mFallSpeedMax;
    f32 mLongFallDistance;
    f32 mFallWallScaleVelocity;
    s32 mDownFallFrameMin;
    f32 mGravityWallSlide;
    f32 mWallHeightLowLimit;
    f32 mWallKeepDegree;
    s32 mWallKeepFrame;
    f32 mWallJumpGravity;
    f32 mWallJumpHSpeed;
    f32 mWallJumpPower;
    s32 mWallJumpInvalidateInputFrame;
    s32 mWallInhibitAfterPunch;
    f32 mWallFollowAngleH;
    f32 mWallFollowAngleV;
    f32 mWallCatchDegree;
    f32 mWallCatchHeightEdgeTop;
    f32 mWallCatchHeightBottom;
    f32 mWallCatchKeepDegree;
    f32 mWallCatchMoveDegree;
    f32 mWallCatchMoveSpeed;
    f32 mWallCatchMoveHeightRange;
    s32 mWallCatchMoveinterpolate;
    s32 mWallCatchMoveFrame;
    s32 mWallCatchMoveFrameFast;
    s32 mWallCatchMoveFrameSwing;
    f32 mWallCatchInputRepeatAngle;
    f32 mWallClimbDegree;
    s32 mWallClimbJumpStartFrame;
    s32 mWallClimbJumpEndFrame;
    s32 mWallClimbStartFrame;
    f32 mWallClimbGravity;
    f32 mWallFallJumpSpeed;
    f32 mWallClimbJumpSpeedV;
    f32 mWallClimbJumpSpeedH;
    f32 mWallClimbJumpGravity;
    s32 mWallClimbJumpInvalidFrame;
    f32 mWallCatchHipLocalOffset;
    f32 mWallCatchHipStability;
    f32 mWallCatchHipFriction;
    f32 mWallCatchHipLimitDegree;
    f32 mWallCatchStainAreaOffset;
    f32 mGrabCeilRange;
    f32 mGrabCeilBodyRadius;
    f32 mGrabCeilLeaveSpeedMin;
    f32 mGrabCeilLeavePopPower;
    f32 mGrabCeilLeavePopGravity;
    f32 mGrabCeilSwingStartOffset;
    f32 mGrabCeilReverseInputBorder;
    f32 mGrabCeilInputPowerBorder;
    f32 mGrabCeilSwingWaitEnergy;
    f32 mGrabCeilEnableJumpEnergy;
    f32 mGrabCeilEnableJumpEnergyMax;
    f32 mGrabCeilJumpForceAngle;
    f32 mGrabCeilJumpPower;
    f32 mGrabCeilJumpMoveMin;
    f32 mGrabCeilJumpMoveMax;
    f32 mGrabCeilJumpGravity;
    s32 mGrabCeilJumpInvalidFrame;
    s32 mGrabCeilEnableNextFrame;
    s32 mGrabCeilEnableFallSnapFrame;
    s32 mPoleClimbPreInputSwing;
    f32 mPoleClimbInputRepeatAngle;
    f32 mPoleClimbInputDegreeMove;
    f32 mPoleClimbCatchRange;
    f32 mPoleClimbCatchRangeMin;
    f32 mPoleClimbCatchRangeMax;
    f32 mPoleClimbJointAngleMin;
    f32 mPoleClimbJointAngleMax;
    f32 mPoleClimbJointRangeMin;
    f32 mPoleClimbJointRangeMax;
    f32 mPoleClimbMoveWallDegree;
    f32 mPoleClimbUpMargine;
    f32 mPoleClimbUpSpeed;
    s32 mPoleClimbUpFrame;
    s32 mPoleClimbUpFrameFast;
    s32 mPoleClimbUpFrameSwing;
    f32 mPoleClimbDownSpeed;
    f32 mPoleClimbDownSpeedFast;
    f32 mPoleClimbDownSpeedSwing;
    s32 mPoleClimbDownFrame;
    s32 mPoleClimbDownKeepTime;
    f32 mPoleClimbTurnDist;
    s32 mPoleClimbTurnFrame;
    s32 mPoleClimbTurnStopFrame;
    s32 mPoleTopStartFrame;
    s32 mPoleTopEndFrame;
    f32 mPoleTopTurnSpeed;
    f32 mPoleTopEndUnderOffsetY;
    s32 mGroundSpinFrame;
    f32 mGroundSpinMoveSpeedMax;
    f32 mGroundSpinAccelRate;
    f32 mGroundSpinBrakeRate;
    f32 mSpinJumpGravity;
    f32 mSpinJumpPower;
    f32 mSpinJumpMoveSpeedMax;
    f32 mSpinJumpDownFallInitSpeed;
    f32 mSpinJumpDownFallPower;
    f32 mSpinJumpDownFallSpeedMax;
    f32 mSquatBrakeEndSpeed;
    f32 mSquatAccelRate;
    f32 mSquatBrakeRate;
    f32 mSquatBrakeRateOnSkate;
    f32 mSquatBrakeSideAccel;
    f32 mSquatBrakeSideRate;
    f32 mSquatBrakeSideAccelOnSkate;
    f32 mSquatBrakeSideRateOnSkate;
    f32 mSquatBrakeSideMaxSpeedRate;
    f32 mSquatWalkSpeed;
    f32 mSquatWalkTurnSpeed;
    s32 mSquatWalkTurnFrame;
    f32 mSquatJumpCeilSlideSpeed2D;
    f32 mHipDropSpeed;
    f32 mHipDropGravity;
    f32 mHipDropSpeedMax;
    s32 mHipDropLandCancelFrame;
    f32 mHipDropHeight;
    s32 mHipDropMsginterval;
    f32 mJumpHipDropPower;
    s32 mJumpHipDropPermitBeginFrame;
    s32 mJumpHipDropPermitEndFrame;
    f32 mHeadSlidingSpeed;
    f32 mHeadSlidingSpeedMin;
    f32 mHeadSlidingBrake;
    f32 mHeadSlidingSideAccel;
    f32 mHeadSlidingJump;
    f32 mHeadSlidingGravityAir;
    f32 mSwimCenterOffset;
    f32 mSwimWallCatchOffset;
    f32 mSwimRisePower;
    f32 mSwimRiseSpeedMax;
    s32 mSwimRiseFrame;
    f32 mSwimGravity;
    f32 mSwimGravityWalk;
    f32 mSwimFallSpeedMax;
    f32 mSwimFloorAccelH;
    f32 mSwimFloorSpeedMaxH;
    f32 mSwimHighAccelH;
    f32 mSwimHighSpeedMaxH;
    f32 mSwimLowAccelH;
    f32 mSwimLowSpeedMaxH;
    f32 mSwimBrakeRateH;
    f32 mSwimWallHitSpeedMinH;
    s32 mSwimHighAccelPermitFrame;
    f32 mSwimFlowFieldBlend;
    f32 mSwimWalkAnimMinRate;
    f32 mSwimWalkAnimMaxRate;
    f32 mSwimWalkMaxSpeed;
    f32 mSwimSpinCapUpPower;
    f32 mSwimSpinCapUpSpeedMax;
    f32 mSwimRotStartAngle;
    f32 mSwimRotFastAngle;
    s32 mSwimRotAccelFrame;
    s32 mSwimRotAccelFrameFast;
    s32 mSwimRotBrakeFrame;
    f32 mSwimRotSpeedChangeStart;
    f32 mSwimRotSpeedForward;
    f32 mSwimRotSpeedMax;
    f32 mSwimSurfaceAccelH;
    f32 mSwimSurfaceSpeedMaxH;
    s32 mSwimSurfaceSpinCapFrame;
    f32 mSwimSurfaceSpinCapSpeedMaxH;
    f32 mSwimSurfaceStartDist;
    f32 mSwimSurfaceEndDist;
    f32 mSwimSurfaceGravity;
    f32 mSwimSurfaceBaseHeight;
    f32 mSwimSurfaceSpring;
    f32 mSwimSurfaceDamper;
    s32 mSwimSurfaceDamperStart;
    s32 mSwimSurfaceDamperFrame;
    f32 mSwimSurfaceEnableJumpHeight;
    s32 mSwimSurfacePreInputJumpFrame;
    f32 mSwimSurfaceMoveSpring;
    f32 mSwimSurfaceMoveDamper;
    f32 mSwimSurfaceMoveBaseHeight;
    f32 mSwimRunSurfaceBaseHeight;
    f32 mSwimRunSurfaceApproachRate;
    f32 mSwimRunSurfaceApproachLimit;
    f32 mSwimRunSurfaceBrakeBorder;
    f32 mSwimRunSurfaceBrakeH;
    f32 mSwimRunSurfaceApproachBorderMax;
    f32 mSwimRunSurfaceApproachBorderMin;
    f32 mSwimRunSurfaceApproachRateMin;
    f32 mSwimFallInSpeed;
    f32 mSwimFallInBrakeH;
    f32 mSwimFallInBrakeV;
    f32 mSwimHeadInBrakeH;
    f32 mSwimHeadInBrakeV;
    f32 mSwimHeadInRisePower;
    f32 mSwimHeadInRiseSpeedMax;
    f32 mSwimHeadInSurfaceHeight;
    s32 mSwimFallInForceSurfaceFrame;
    s32 mSwimFallInvalidJumpFrame;
    f32 mSwimDiveStartSpeed;
    f32 mSwimDiveBrake;
    f32 mSwimDiveEndSpeed;
    s32 mSwimDiveLandCount;
    s32 mSwimDiveLandCancelFrame;
    s32 mSwimDiveNoBrakeFrame;
    s32 mSwimDiveButtonValidFrame;
    s32 mSwimDiveEndFrame;
    f32 mSwimDiveInBrakeH;
    f32 mSwimDiveInBrakeV;
    f32 mSwimDiveInRisePower;
    f32 mSwimDiveInRiseSpeedMax;
    f32 mSwimDiveInSurfaceHeight;
    s32 mSwimDiveInKeepFrame;
    s32 mSwimHeadSlidingFrame;
    s32 mSwimHeadSlidingBrakeFrame;
    f32 mSwimHeadSlidingSpeed;
    f32 mSwimHeadSlidingSpeedEnd;
    f32 mSwimHeadSlidingBrake;
    f32 mSwimHeadSlidingSideAccel;
    f32 mSwimHeadSlidingJump;
    f32 mSwimHeadSlidingGravity;
    s32 mSwimHeadSlidingEndBrakeFrame;
    s32 mSwimHeadSlidingEndSpeedMin;
    f32 mSwimJumpHipDropSpeed;
    f32 mSwimJumpHipDropBrakeV;
    f32 mSwimJumpHipDropBrakeVCeiling;
    f32 mSwimJumpHipDropGravity;
    f32 mSwimJumpHipDropCancelSpeed;
    f32 mSwimJumpHipDropAccelH;
    f32 mSwimJumpHipDropMoveSpeedH;
    f32 mSwimJumpHipDropPopSpeed;
    f32 mSwimJumpHipDropPopJumpAdd;
    f32 mSwimTramplePower;
    f32 mDiveTramplePower;
    s32 mDiveTrampleCancelFrame;
    f32 mDamageSwimPushPower;
    f32 mDamageSwimGravity;
    s32 mDamageSwimCancelFrame;
    f32 mDamageSwimSurfaceGravity;
    f32 mDamageSwimSurfaceHopPower;
    f32 mDamageSwimSurfacePushPower;
    f32 mDamageSwimSurfaceLandSpeed;
    f32 mDamageSwimSurfaceLandBrake;
    f32 mDamageSwimSurfaceLandEndSpeed;
    s32 mDamageSwimSurfaceCancelFrame;
    f32 mDamageSwimBrakeRateGround;
    s32 mOxygenReduceFrame;
    s32 mOxygenNoReduceFrame;
    s32 mOxygenRecoveryFrame;
    s32 mOxygenDamageinterval;
    s32 mIceWaterDamageinterval;
    s32 mIceWaterRecoveryFrame;
    f32 mMoveAnimSpeedMax;
    f32 mAnimFrameRateSpeedMin;
    f32 mRunBorderSpeed;
    f32 mRunBlendRange;
    f32 mDashBorderSpeed;
    f32 mDashBlendRange;
    f32 mDashFastBorderSpeed;
    f32 mDashFastBlendRange;
    f32 mAnimFrameRateSpeedMax;
    f32 mAnimFrameRateRunStart;
    f32 mAnimFrameRateMinRun;
    f32 mAnimFrameRateMaxRun;
    f32 mAnimFrameRateMaxDash;
    f32 mAnimFrameRateMaxDashFast;
    f32 mRunStartPlayFrameScale;
    s32 mRunStartBlendFrame;
    f32 mDamageFireRunAnimRate;
    f32 mRunSkateAnimSpeedOffset;
    f32 mAnimFrameRateRange2D;
    f32 mAnimFrameRateMinRun2D;
    f32 mAnimFrameRateMaxRun2D;
    s32 mIKBlendFrameRun;
    f32 mIKBlendRateRunMin;
    f32 mIKBlendRateRunMax;
    f32 mRollingAnimBorderSpeedMin;
    f32 mRollingAnimBorderSpeedMax;
    f32 mRollingAnimFrameRateMin;
    f32 mRollingAnimFrameRateMax;
    s32 mSwimPaddleAniminterval;
    s32 mSwimPaddleAnimRateintervalMax;
    s32 mSwimPaddleAnimRateintervalMin;
    f32 mSwimPaddleAnimMaxRate;
    f32 mSwimBentForwardMax;
    f32 mSwimBentForwardBlendRate;
    f32 mSwimBentSideMax;
    f32 mSwimBentSpineMax;
    f32 mSwimBentSideBlendRate;
    f32 mSwimBentFrontMax;
    f32 mSwimBentFrontBlendRate;
    f32 mSwimWalkAnimSpeedMax;
    f32 mSwimWalkAnimSpeedMin;
    f32 mSwimWalkAnimFrameRateMax;
    f32 mSwimWalkAnimFrameRateMin;
    f32 mSandSinkBorderMin;
    f32 mSandSinkBorderMax;
    f32 mSandSinkBorderRateMin;
    f32 mSandSinkBorderRateMax;
    f32 mSandSinkFrameRateMin;
    f32 mSandSinkFrameRateMax;
    s32 mLookAtEyeKeepFrame;
    s32 mLookAtEyeKeepFrameInSight;
    s32 mLookAtEyeKeepFrameWait;
    f32 mLookAtEyeDistance;
    f32 mLookAtEyeAngleMinH;
    f32 mLookAtEyeAngleMinInSightH;
    f32 mLookAtEyeAngleMaxH;
    f32 mLookAtEyeAngleMinV;
    f32 mLookAtEyeAngleMinInSightV;
    f32 mLookAtEyeAngleMaxV;
    f32 mTiltEyeBorderStart;
    f32 mTiltEyeBorderEnd;
    f32 mTiltEyeAngleScale;
    f32 mCenterTiltRateMax;
    f32 mNoseChildLocalOffset;
    f32 mNoseStability;
    f32 mNoseFriction;
    f32 mNoseLimitDegree;
    f32 mMustacheChildLocalOffset;
    f32 mMustacheStability;
    f32 mMustacheFriction;
    f32 mMustacheLimitDegree;
    s32 mCapinterpolateFrame;
    f32 mCapChildLocalOffset;
    f32 mCapStability;
    f32 mCapFriction;
    f32 mCapLimitDegree;
    f32 mCapTransStability;
    f32 mCapTransFriction;
    f32 mCapTransLimit;
    s32 mCapManHeroEyesWaitAppearFrame;
    s32 mDeadWipeStartDamage;
    s32 mDeadWipeWaitDamage;
    s32 mDeadWipeStartAbyss;
    s32 mDeadWipeWaitAbyss;
    s32 mDeadWipeStartAbyssWithCapMsg;
    s32 mDeadWipeWaitAbyssWithCapMsg;
    s32 mDeadWipeStartPress;
    s32 mDeadWipeWaitPress;
    s32 mDeadWipeStartSandSink;
    s32 mDeadWipeWaitSandSink;
    s32 mDeadWipeStartNoOxygen;
    s32 mDeadWipeWaitNoOxygen;
    s32 mDeadWipeStartIceWater;
    s32 mDeadWipeWaitIceWater;
    f32 mCoinDashSpeed;
    f32 mCoinDashSpeedLimit;
    f32 mAdditionalSpeedLimit;
};
