#pragma once

#include "al/byaml/ByamlIter.h"
#include "al/hio/HioNode.h"

class PlayerConst : al::HioNode {
public:
    PlayerConst();
    PlayerConst(const al::ByamlIter&);

    virtual float getGravity() const;
    virtual float getFrictionAttack() const;
    virtual float getPushPower() const;
    virtual float getWaitPoseDegreeMax() const;
    virtual float getHillPoseDegreeMax() const;
    virtual float getTiltPoseDegreeMax() const;
    virtual float getSlerpQuatRate() const;
    virtual float getSlerpQuatRateWait() const;
    virtual float getSlerpQuatGrav() const;
    virtual int getPreInputFrameCapThrow() const;
    virtual int getEnableActionFrameCapCatch() const;
    virtual float getJumpPowerCapCatch() const;
    virtual float getJumpGravityCapCatch() const;
    virtual int getRunTimeContinuousThrow() const;
    virtual float getRunSpeedMaxContinuousThrow() const;
    virtual int getRunAccelFrameContinuousThrow() const;
    virtual float getSeparateCheckHeight() const;
    virtual float getSeparateOffsetLerpRate() const;
    virtual float getSeparateEnableThrowHeight() const;
    virtual float getTall() const;
    virtual float getCollisionRadius() const;
    virtual float getCollisionRadiusSquat() const;
    virtual float getCollisionRadiusStand() const;
    virtual float getCollisionSmallStepHeight() const;
    virtual float getCollisionResetLimit() const;
    virtual float getReflectCeilingPower() const;
    virtual float getReflectTossPower() const;
    virtual float getReflectUpperPunchScaleH() const;
    virtual float getCollisionHitDownAngleH() const;
    virtual float getCollisionHitDownEscapeAngleV() const;
    virtual float getShadowDropHeightScale() const;
    virtual float getShadowDropNormalAdd() const;
    virtual float getShadowDropLengthMin() const;
    virtual float getShadowDropLengthMax() const;
    virtual float getShadowDropLengthExtend() const;
    virtual float getGravityDamage() const;
    virtual float getHopPowerDamage() const;
    virtual float getPushPowerDamage() const;
    virtual int getDamageCancelFrame() const;
    virtual int getDamageInvalidCount() const;
    virtual int getDamageInvalidCountRecovery() const;
    virtual int getDamageInvalidCountAbyss() const;
    virtual float getNormalMinSpeed2D() const;
    virtual float getNormalMaxSpeed2D() const;
    virtual float getDashMaxSpeed2D() const;
    virtual int getNormalAccelFrame2D() const;
    virtual int getDashAccelFrame2D() const;
    virtual int getNormalDashAnimFrame2D() const;
    virtual int getNormalBrakeFrame2D() const;
    virtual int getStickOnBrakeFrame2D() const;
    virtual int getBrakeTurnStartFrame2D() const;
    virtual float getTurnEndSpeedRate2D() const;
    virtual float getJumpPowerMin2DArea() const;
    virtual float getJumpPowerMax2DArea() const;
    virtual float getJumpPowerMinBorder2D() const;
    virtual float getJumpPowerMaxBorder2D() const;
    virtual float getGravityMove() const;
    virtual float getNormalMaxSpeed() const;
    virtual float getNormalMinSpeed() const;
    virtual int getNormalAccelFrame() const;
    virtual float getRunAccelAverageScale() const;
    virtual int getNormalBrakeFrame() const;
    virtual float getDashJudgeSpeed() const;
    virtual int getStickOnBrakeFrame() const;
    virtual int getNormalDashAnimFrame() const;
    virtual float getRunAfterTurnSpeedMax() const;
    virtual float getRunAfterTurnScale() const;
    virtual int getRunAfterTurnFrame() const;
    virtual int getBrakeTurnStartFrame() const;
    virtual float getBrakeOnSpeedRate() const;
    virtual int getBrakeOnCounterBorder() const;
    virtual int getWallPushFrame() const;
    virtual int getRunDeepDownFrame() const;
    virtual int getRunDeepDownMargine() const;
    virtual int getQuickTurnJumpFrame() const;
    virtual int getRoundAccelFrame() const;
    virtual int getRoundBrakeFrame() const;
    virtual float getRoundFastDegree() const;
    virtual int getRoundAccelFrameFast() const;
    virtual float getRoundMinDegree() const;
    virtual int getRoundBrakeFrameForce() const;
    virtual float getRoundFastDegreeForce() const;
    virtual float getRoundLimitDegreeForce() const;
    virtual float getRoundLimitDegreeForceFast() const;
    virtual int getRoundAccelFrameForceFast() const;
    virtual float getRoundLimitDegreeMin() const;
    virtual float getRoundLimitDegree() const;
    virtual int getIceAccelFrame() const;
    virtual int getIceBrakeFrame() const;
    virtual int getIceBrakeFrameHigh() const;
    virtual int getIceBrakeFrameWall() const;
    virtual int getIceRoundAccelFrame() const;
    virtual int getIceRoundAccelFrameFast() const;
    virtual int getIceRoundBrakeFrame() const;
    virtual float getIceRoundFastDegree() const;
    virtual float getIceRoundMinDegree() const;
    virtual float getIceRoundLimitDegree() const;
    virtual float getHillAddSpeed() const;
    virtual float getHillSubSpeed() const;
    virtual int getHillAccelAddFrame() const;
    virtual int getHillAccelSubFrame() const;
    virtual float getHillAccelSubAngleMin() const;
    virtual float getHillAccelSubAngleMax() const;
    virtual float getStandAngleMin() const;
    virtual float getStandAngleMax() const;
    virtual float getHillAngleSpeedMin() const;
    virtual float getHillAngleSpeedMax() const;
    virtual int getSpinCapThrowFrame() const;
    virtual int getSpinCapThrowFrameAir() const;
    virtual int getSpinCapThrowFrameSwim() const;
    virtual int getSpinCapThrowFrameSwing() const;
    virtual int getSpinCapThrowFrameContinuous() const;
    virtual int getSpinAttackFrame() const;
    virtual int getSpinBrakeFrame() const;
    virtual float getSpinAirJumpPower() const;
    virtual float getSpinAirSpeedMax() const;
    virtual float getGravitySpinAir() const;
    virtual float getSlerpQuatRateSpinAir() const;
    virtual float getSpinBrakeRate() const;
    virtual float getSpinBrakeSideAccel() const;
    virtual float getSpinBrakeSideBrakeRate() const;
    virtual float getSpinBrakeSideMaxSpeedRate() const;
    virtual float getSpinRoundLimitDegree() const;
    virtual float getDamageFireJumpPower1st() const;
    virtual float getDamageFireJumpPower2nd() const;
    virtual float getDamageFireJumpMoveSpeed() const;
    virtual float getDamageFireCeilHitSpeed() const;
    virtual float getDamageFireGravity() const;
    virtual int getDamageFireNoGravityFrame() const;
    virtual int getDamageFireRunTime() const;
    virtual float getDamageFireRunSpeed() const;
    virtual float getDamageFireRunBrakeFrame() const;
    virtual int getSandSinkDeadTime() const;
    virtual int getSandSinkBrakeHeightH() const;
    virtual int getSandSinkBrakeHeightV() const;
    virtual float getSandSinkHeight() const;
    virtual float getSandSinkCapThrow() const;
    virtual float getSandSinkBrakeMinH() const;
    virtual float getSandSinkBrakeMaxH() const;
    virtual float getSandSinkBrakeMinV() const;
    virtual float getSandSinkBrakeMaxV() const;
    virtual float getSlopeSlideAngleStart() const;
    virtual float getSlopeSlideAngleEnd() const;
    virtual float getSlopeSlideAccel() const;
    virtual float getSlopeSlideBrake() const;
    virtual float getSlopeSlideMaxSpeed() const;
    virtual float getSlopeSlideSpeedEnd() const;
    virtual float getSlopeSlideSideAccel() const;
    virtual float getSlopeSlideSideBrake() const;
    virtual float getSlopeSlideSideMaxSpeed() const;
    virtual float getSlopeTurnDegree() const;
    virtual int getSlideInvalidFrame() const;
    virtual int getSlopeForceFrame() const;
    virtual float getSlopeSlideForceSideAccel() const;
    virtual float getSlopeSlideForceSideBrake() const;
    virtual float getSlopeSlideForceSideMaxSpeed() const;
    virtual float getSlopeSlideForceTurnDegree() const;
    virtual float getSlopeRollingSpeedStart() const;
    virtual float getSlopeRollingSpeedBoost() const;
    virtual float getSlopeRollingMaxSpeed() const;
    virtual int getSlopeRollingFrameMinBoost() const;
    virtual int getSlopeRollingFrameMin() const;
    virtual float getSlopeRollingStartJumpPower() const;
    virtual float getSlopeRollingStartSlideSpeed() const;
    virtual float getSlopeRollingAccel() const;
    virtual float getSlopeRollingBrake() const;
    virtual float getSlopeRollingAgainst() const;
    virtual float getSlopeRollingAnglePowerMax() const;
    virtual float getSlopeRollingSpeedEnd() const;
    virtual float getSlopeRollingSideAccel() const;
    virtual float getSlopeRollingSideBrake() const;
    virtual float getSlopeRollingSideMaxSpeed() const;
    virtual int getSlopeRollingUnRollFrame() const;
    virtual float getSlopeRollingEndBrake() const;
    virtual float getSlopeRollingEndBrakeEndSpeed() const;
    virtual float getSlopeRollingReStartAccel() const;
    virtual float getSlopeRollingReStartMaxAdd() const;
    virtual int getSlopeRollingReStartInterval() const;
    virtual int getSlopeRollingReStartSwing() const;
    virtual int getSlopeRollingReStartCharge() const;
    virtual int getSlopeRollingReStartForce() const;
    virtual float getSlopeRollingAccelOnSkate() const;
    virtual float getSlopeRollingSideAccelOnSkate() const;
    virtual float getSlopeRollingBrakeOnSkate() const;
    virtual int getExtendFrame() const;
    virtual float getJumpInertiaRate() const;
    virtual float getJumpPowerMin() const;
    virtual float getJumpPowerMax() const;
    virtual float getJumpGravity() const;
    virtual float getJumpBaseSpeedMax() const;
    virtual float getJumpMoveSpeedMin() const;
    virtual float getJumpMoveSpeedMax() const;
    virtual float getJumpAccelFront() const;
    virtual float getJumpAccelBack() const;
    virtual float getJumpAccelTurn() const;
    virtual float getJumpTurnAngleStart() const;
    virtual float getJumpTurnAngleLimit() const;
    virtual float getJumpTurnAngleFast() const;
    virtual float getJumpTurnAngleFastLimit() const;
    virtual int getJumpTurnAccelFrame() const;
    virtual int getJumpTurnAccelFrameFast() const;
    virtual int getJumpTurnBrakeFrame() const;
    virtual float getTrampleGravity() const;
    virtual float getTrampleJumpPower() const;
    virtual float getTrampleHighGravity() const;
    virtual float getTrampleHighJumpPower() const;
    virtual float getTrampleGravity2D() const;
    virtual float getTrampleJumpPower2D() const;
    virtual float getTrampleHighGravity2D() const;
    virtual float getTrampleHighJumpPower2D() const;
    virtual float getTrampleHipDropGravity() const;
    virtual float getTrampleHipDropJumpPower() const;
    virtual float getTrampleRisingBrakeVelH() const;
    virtual float getTrampleJumpCodePower() const;
    virtual float getTrampleJumpCodePowerSmall() const;
    virtual float getCapLeapFrogJumpGravity() const;
    virtual float getCapLeapFrogJumpPower() const;
    virtual float getCapLeapFrogJumpPowerAir() const;
    virtual float getObjLeapFrogJumpPower() const;
    virtual float getObjLeapFrogJumpPowerHigh() const;
    virtual float getCapHeadSpringJumpGravity() const;
    virtual float getCapHeadSpringJumpPower() const;
    virtual float getCapHeadSpringJumpGravityHigh() const;
    virtual float getCapHeadSpringJumpPowerHigh() const;
    virtual float getCapHeadSpringSpeedMax() const;
    virtual int getContinuousJumpPreInputFrame() const;
    virtual int getContinuousJumpCount() const;
    virtual int getContinuousJumpTimer() const;
    virtual float getContinuousJumpPowerMin() const;
    virtual float getJumpPowerMax2nd() const;
    virtual float getJumpGravity2nd() const;
    virtual float getJumpPowerMax3rd() const;
    virtual float getJumpGravity3rd() const;
    virtual float getSpinFlowerJumpGravity() const;
    virtual float getSpinFlowerJumpFallSpeedMax() const;
    virtual float getSpinFlowerJumpMovePower() const;
    virtual float getSpinFlowerJumpVelMax() const;
    virtual int getSpinFlowerJumpStayFrame() const;
    virtual float getSpinFlowerJumpStaySpeedMax() const;
    virtual float getSpinFlowerJumpNoInputBrake() const;
    virtual float getSpinFlowerJumpDownFallInitSpeed() const;
    virtual float getSpinFlowerJumpDownFallPower() const;
    virtual float getSpinFlowerJumpDownFallSpeedMax() const;
    virtual float getJumpGravityForceRun() const;
    virtual float getJumpPowerForceRun() const;
    virtual float getCapCatchPopPower() const;
    virtual float getCapCatchPopGravity() const;
    virtual float getSquatJumpGravity() const;
    virtual float getSquatJumpPower() const;
    virtual float getSquatJumpBackPower() const;
    virtual float getSquatJumpMovePowerFront() const;
    virtual float getSquatJumpMovePowerSide() const;
    virtual float getSquatJumpMoveSpeedMax() const;
    virtual float getTurnJumpGravity() const;
    virtual float getTurnJumpPower() const;
    virtual float getTurnJumpVelH() const;
    virtual float getTurnJumpBrake() const;
    virtual float getTurnJumpAccel() const;
    virtual float getTurnJumpSideAccel() const;
    virtual float getLongJumpAccel() const;
    virtual float getLongJumpBrake() const;
    virtual float getLongJumpSideAccel() const;
    virtual float getLongJumpGravity() const;
    virtual float getLongJumpJumpPow() const;
    virtual float getLongJumpMovePow() const;
    virtual float getLongJumpInitSpeed() const;
    virtual float getLongJumpSpeed() const;
    virtual float getLongJumpSpeedMin() const;
    virtual int getContinuousLongJumpCount() const;
    virtual int getContinuousLongJumpTimer() const;
    virtual float getGravityAir() const;
    virtual float getFrictionAir() const;
    virtual float getFallSpeedMax() const;
    virtual float getLongFallDistance() const;
    virtual float getFallWallScaleVelocity() const;
    virtual int getDownFallFrameMin() const;
    virtual float getGravityWallSlide() const;
    virtual float getWallHeightLowLimit() const;
    virtual float getWallKeepDegree() const;
    virtual int getWallKeepFrame() const;
    virtual float getWallJumpGravity() const;
    virtual float getWallJumpHSpeed() const;
    virtual float getWallJumpPower() const;
    virtual int getWallJumpInvalidateInputFrame() const;
    virtual int getWallInhibitAfterPunch() const;
    virtual float getWallFollowAngleH() const;
    virtual float getWallFollowAngleV() const;
    virtual float getWallCatchDegree() const;
    virtual float getWallCatchHeightEdgeTop() const;
    virtual float getWallCatchHeightBottom() const;
    virtual float getWallCatchKeepDegree() const;
    virtual float getWallCatchMoveDegree() const;
    virtual float getWallCatchMoveSpeed() const;
    virtual float getWallCatchMoveHeightRange() const;
    virtual int getWallCatchMoveInterpolate() const;
    virtual int getWallCatchMoveFrame() const;
    virtual int getWallCatchMoveFrameFast() const;
    virtual int getWallCatchMoveFrameSwing() const;
    virtual float getWallCatchInputRepeatAngle() const;
    virtual float getWallClimbDegree() const;
    virtual int getWallClimbJumpStartFrame() const;
    virtual int getWallClimbJumpEndFrame() const;
    virtual int getWallClimbStartFrame() const;
    virtual float getWallClimbGravity() const;
    virtual float getWallFallJumpSpeed() const;
    virtual float getWallClimbJumpSpeedV() const;
    virtual float getWallClimbJumpSpeedH() const;
    virtual float getWallClimbJumpGravity() const;
    virtual int getWallClimbJumpInvalidFrame() const;
    virtual float getWallCatchHipLocalOffset() const;
    virtual float getWallCatchHipStability() const;
    virtual float getWallCatchHipFriction() const;
    virtual float getWallCatchHipLimitDegree() const;
    virtual float getWallCatchStainAreaOffset() const;
    virtual float getGrabCeilRange() const;
    virtual float getGrabCeilBodyRadius() const;
    virtual float getGrabCeilLeaveSpeedMin() const;
    virtual float getGrabCeilLeavePopPower() const;
    virtual float getGrabCeilLeavePopGravity() const;
    virtual float getGrabCeilSwingStartOffset() const;
    virtual float getGrabCeilReverseInputBorder() const;
    virtual float getGrabCeilInputPowerBorder() const;
    virtual float getGrabCeilSwingWaitEnergy() const;
    virtual float getGrabCeilEnableJumpEnergy() const;
    virtual float getGrabCeilEnableJumpEnergyMax() const;
    virtual float getGrabCeilJumpForceAngle() const;
    virtual float getGrabCeilJumpPower() const;
    virtual float getGrabCeilJumpMoveMin() const;
    virtual float getGrabCeilJumpMoveMax() const;
    virtual float getGrabCeilJumpGravity() const;
    virtual int getGrabCeilJumpInvalidFrame() const;
    virtual int getGrabCeilEnableNextFrame() const;
    virtual int getGrabCeilEnableFallSnapFrame() const;
    virtual int getPoleClimbPreInputSwing() const;
    virtual float getPoleClimbInputRepeatAngle() const;
    virtual float getPoleClimbInputDegreeMove() const;
    virtual float getPoleClimbCatchRange() const;
    virtual float getPoleClimbCatchRangeMin() const;
    virtual float getPoleClimbCatchRangeMax() const;
    virtual float getPoleClimbJointAngleMin() const;
    virtual float getPoleClimbJointAngleMax() const;
    virtual float getPoleClimbJointRangeMin() const;
    virtual float getPoleClimbJointRangeMax() const;
    virtual float getPoleClimbMoveWallDegree() const;
    virtual float getPoleClimbUpMargine() const;
    virtual float getPoleClimbUpSpeed() const;
    virtual int getPoleClimbUpFrame() const;
    virtual int getPoleClimbUpFrameFast() const;
    virtual int getPoleClimbUpFrameSwing() const;
    virtual float getPoleClimbDownSpeed() const;
    virtual float getPoleClimbDownSpeedFast() const;
    virtual float getPoleClimbDownSpeedSwing() const;
    virtual int getPoleClimbDownFrame() const;
    virtual int getPoleClimbDownKeepTime() const;
    virtual float getPoleClimbTurnDist() const;
    virtual int getPoleClimbTurnFrame() const;
    virtual int getPoleClimbTurnStopFrame() const;
    virtual int getPoleTopStartFrame() const;
    virtual int getPoleTopEndFrame() const;
    virtual float getPoleTopTurnSpeed() const;
    virtual float getPoleTopEndUnderOffsetY() const;
    virtual int getGroundSpinFrame() const;
    virtual float getGroundSpinMoveSpeedMax() const;
    virtual float getGroundSpinAccelRate() const;
    virtual float getGroundSpinBrakeRate() const;
    virtual float getSpinJumpGravity() const;
    virtual float getSpinJumpPower() const;
    virtual float getSpinJumpMoveSpeedMax() const;
    virtual float getSpinJumpDownFallInitSpeed() const;
    virtual float getSpinJumpDownFallPower() const;
    virtual float getSpinJumpDownFallSpeedMax() const;
    virtual float getSquatBrakeEndSpeed() const;
    virtual float getSquatAccelRate() const;
    virtual float getSquatBrakeRate() const;
    virtual float getSquatBrakeRateOnSkate() const;
    virtual float getSquatBrakeSideAccel() const;
    virtual float getSquatBrakeSideRate() const;
    virtual float getSquatBrakeSideAccelOnSkate() const;
    virtual float getSquatBrakeSideRateOnSkate() const;
    virtual float getSquatBrakeSideMaxSpeedRate() const;
    virtual float getSquatWalkSpeed() const;
    virtual float getSquatWalkTurnSpeed() const;
    virtual int getSquatWalkTurnFrame() const;
    virtual float getSquatJumpCeilSlideSpeed2D() const;
    virtual float getHipDropSpeed() const;
    virtual float getHipDropGravity() const;
    virtual float getHipDropSpeedMax() const;
    virtual int getHipDropLandCancelFrame() const;
    virtual float getHipDropHeight() const;
    virtual int getHipDropMsgInterval() const;
    virtual float getJumpHipDropPower() const;
    virtual int getJumpHipDropPermitBeginFrame() const;
    virtual int getJumpHipDropPermitEndFrame() const;
    virtual float getHeadSlidingSpeed() const;
    virtual float getHeadSlidingSpeedMin() const;
    virtual float getHeadSlidingBrake() const;
    virtual float getHeadSlidingSideAccel() const;
    virtual float getHeadSlidingJump() const;
    virtual float getHeadSlidingGravityAir() const;
    virtual float getSwimCenterOffset() const;
    virtual float getSwimWallCatchOffset() const;
    virtual float getSwimRisePower() const;
    virtual float getSwimRiseSpeedMax() const;
    virtual int getSwimRiseFrame() const;
    virtual float getSwimGravity() const;
    virtual float getSwimGravityWalk() const;
    virtual float getSwimFallSpeedMax() const;
    virtual float getSwimFloorAccelH() const;
    virtual float getSwimFloorSpeedMaxH() const;
    virtual float getSwimHighAccelH() const;
    virtual float getSwimHighSpeedMaxH() const;
    virtual float getSwimLowAccelH() const;
    virtual float getSwimLowSpeedMaxH() const;
    virtual float getSwimBrakeRateH() const;
    virtual float getSwimWallHitSpeedMinH() const;
    virtual int getSwimHighAccelPermitFrame() const;
    virtual float getSwimFlowFieldBlend() const;
    virtual float getSwimWalkAnimMinRate() const;
    virtual float getSwimWalkAnimMaxRate() const;
    virtual float getSwimWalkMaxSpeed() const;
    virtual float getSwimSpinCapUpPower() const;
    virtual float getSwimSpinCapUpSpeedMax() const;
    virtual float getSwimRotStartAngle() const;
    virtual float getSwimRotFastAngle() const;
    virtual int getSwimRotAccelFrame() const;
    virtual int getSwimRotAccelFrameFast() const;
    virtual int getSwimRotBrakeFrame() const;
    virtual float getSwimRotSpeedChangeStart() const;
    virtual float getSwimRotSpeedForward() const;
    virtual float getSwimRotSpeedMax() const;
    virtual float getSwimSurfaceAccelH() const;
    virtual float getSwimSurfaceSpeedMaxH() const;
    virtual int getSwimSurfaceSpinCapFrame() const;
    virtual float getSwimSurfaceSpinCapSpeedMaxH() const;
    virtual float getSwimSurfaceStartDist() const;
    virtual float getSwimSurfaceEndDist() const;
    virtual float getSwimSurfaceGravity() const;
    virtual float getSwimSurfaceBaseHeight() const;
    virtual float getSwimSurfaceSpring() const;
    virtual float getSwimSurfaceDamper() const;
    virtual int getSwimSurfaceDamperStart() const;
    virtual int getSwimSurfaceDamperFrame() const;
    virtual float getSwimSurfaceEnableJumpHeight() const;
    virtual int getSwimSurfacePreInputJumpFrame() const;
    virtual float getSwimSurfaceMoveSpring() const;
    virtual float getSwimSurfaceMoveDamper() const;
    virtual float getSwimSurfaceMoveBaseHeight() const;
    virtual float getSwimRunSurfaceBaseHeight() const;
    virtual float getSwimRunSurfaceApproachRate() const;
    virtual float getSwimRunSurfaceApproachLimit() const;
    virtual float getSwimRunSurfaceBrakeBorder() const;
    virtual float getSwimRunSurfaceBrakeH() const;
    virtual float getSwimRunSurfaceApproachBorderMax() const;
    virtual float getSwimRunSurfaceApproachBorderMin() const;
    virtual float getSwimRunSurfaceApproachRateMin() const;
    virtual float getSwimFallInSpeed() const;
    virtual float getSwimFallInBrakeH() const;
    virtual float getSwimFallInBrakeV() const;
    virtual float getSwimHeadInBrakeH() const;
    virtual float getSwimHeadInBrakeV() const;
    virtual float getSwimHeadInRisePower() const;
    virtual float getSwimHeadInRiseSpeedMax() const;
    virtual float getSwimHeadInSurfaceHeight() const;
    virtual int getSwimFallInForceSurfaceFrame() const;
    virtual int getSwimFallInvalidJumpFrame() const;
    virtual float getSwimDiveStartSpeed() const;
    virtual float getSwimDiveBrake() const;
    virtual float getSwimDiveEndSpeed() const;
    virtual int getSwimDiveLandCount() const;
    virtual int getSwimDiveLandCancelFrame() const;
    virtual int getSwimDiveNoBrakeFrame() const;
    virtual int getSwimDiveButtonValidFrame() const;
    virtual int getSwimDiveEndFrame() const;
    virtual float getSwimDiveInBrakeH() const;
    virtual float getSwimDiveInBrakeV() const;
    virtual float getSwimDiveInRisePower() const;
    virtual float getSwimDiveInRiseSpeedMax() const;
    virtual float getSwimDiveInSurfaceHeight() const;
    virtual int getSwimDiveInKeepFrame() const;
    virtual int getSwimHeadSlidingFrame() const;
    virtual int getSwimHeadSlidingBrakeFrame() const;
    virtual float getSwimHeadSlidingSpeed() const;
    virtual float getSwimHeadSlidingSpeedEnd() const;
    virtual float getSwimHeadSlidingBrake() const;
    virtual float getSwimHeadSlidingSideAccel() const;
    virtual float getSwimHeadSlidingJump() const;
    virtual float getSwimHeadSlidingGravity() const;
    virtual int getSwimHeadSlidingEndBrakeFrame() const;
    virtual int getSwimHeadSlidingEndSpeedMin() const;
    virtual float getSwimJumpHipDropSpeed() const;
    virtual float getSwimJumpHipDropBrakeV() const;
    virtual float getSwimJumpHipDropBrakeVCeiling() const;
    virtual float getSwimJumpHipDropGravity() const;
    virtual float getSwimJumpHipDropCancelSpeed() const;
    virtual float getSwimJumpHipDropAccelH() const;
    virtual float getSwimJumpHipDropMoveSpeedH() const;
    virtual float getSwimJumpHipDropPopSpeed() const;
    virtual float getSwimJumpHipDropPopJumpAdd() const;
    virtual float getSwimTramplePower() const;
    virtual float getDiveTramplePower() const;
    virtual int getDiveTrampleCancelFrame() const;
    virtual float getDamageSwimPushPower() const;
    virtual float getDamageSwimGravity() const;
    virtual int getDamageSwimCancelFrame() const;
    virtual float getDamageSwimSurfaceGravity() const;
    virtual float getDamageSwimSurfaceHopPower() const;
    virtual float getDamageSwimSurfacePushPower() const;
    virtual float getDamageSwimSurfaceLandSpeed() const;
    virtual float getDamageSwimSurfaceLandBrake() const;
    virtual float getDamageSwimSurfaceLandEndSpeed() const;
    virtual int getDamageSwimSurfaceCancelFrame() const;
    virtual float getDamageSwimBrakeRateGround() const;
    virtual int getOxygenReduceFrame() const;
    virtual int getOxygenNoReduceFrame() const;
    virtual int getOxygenRecoveryFrame() const;
    virtual int getOxygenDamageInterval() const;
    virtual int getIceWaterDamageInterval() const;
    virtual int getIceWaterRecoveryFrame() const;
    virtual float getMoveAnimSpeedMax() const;
    virtual float getAnimFrameRateSpeedMin() const;
    virtual float getRunBorderSpeed() const;
    virtual float getRunBlendRange() const;
    virtual float getDashBorderSpeed() const;
    virtual float getDashBlendRange() const;
    virtual float getDashFastBorderSpeed() const;
    virtual float getDashFastBlendRange() const;
    virtual float getAnimFrameRateSpeedMax() const;
    virtual float getAnimFrameRateRunStart() const;
    virtual float getAnimFrameRateMinRun() const;
    virtual float getAnimFrameRateMaxRun() const;
    virtual float getAnimFrameRateMaxDash() const;
    virtual float getAnimFrameRateMaxDashFast() const;
    virtual float getRunStartPlayFrameScale() const;
    virtual int getRunStartBlendFrame() const;
    virtual float getDamageFireRunAnimRate() const;
    virtual float getRunSkateAnimSpeedOffset() const;
    virtual float getAnimFrameRateRange2D() const;
    virtual float getAnimFrameRateMinRun2D() const;
    virtual float getAnimFrameRateMaxRun2D() const;
    virtual int getIKBlendFrameRun() const;
    virtual float getIKBlendRateRunMin() const;
    virtual float getIKBlendRateRunMax() const;
    virtual float getRollingAnimBorderSpeedMin() const;
    virtual float getRollingAnimBorderSpeedMax() const;
    virtual float getRollingAnimFrameRateMin() const;
    virtual float getRollingAnimFrameRateMax() const;
    virtual int getSwimPaddleAnimInterval() const;
    virtual int getSwimPaddleAnimRateIntervalMax() const;
    virtual int getSwimPaddleAnimRateIntervalMin() const;
    virtual float getSwimPaddleAnimMaxRate() const;
    virtual float getSwimBentForwardMax() const;
    virtual float getSwimBentForwardBlendRate() const;
    virtual float getSwimBentSideMax() const;
    virtual float getSwimBentSpineMax() const;
    virtual float getSwimBentSideBlendRate() const;
    virtual float getSwimBentFrontMax() const;
    virtual float getSwimBentFrontBlendRate() const;
    virtual float getSwimWalkAnimSpeedMax() const;
    virtual float getSwimWalkAnimSpeedMin() const;
    virtual float getSwimWalkAnimFrameRateMax() const;
    virtual float getSwimWalkAnimFrameRateMin() const;
    virtual float getSandSinkBorderMin() const;
    virtual float getSandSinkBorderMax() const;
    virtual float getSandSinkBorderRateMin() const;
    virtual float getSandSinkBorderRateMax() const;
    virtual float getSandSinkFrameRateMin() const;
    virtual float getSandSinkFrameRateMax() const;
    virtual int getLookAtEyeKeepFrame() const;
    virtual int getLookAtEyeKeepFrameInSight() const;
    virtual int getLookAtEyeKeepFrameWait() const;
    virtual float getLookAtEyeDistance() const;
    virtual float getLookAtEyeAngleMinH() const;
    virtual float getLookAtEyeAngleMinInSightH() const;
    virtual float getLookAtEyeAngleMaxH() const;
    virtual float getLookAtEyeAngleMinV() const;
    virtual float getLookAtEyeAngleMinInSightV() const;
    virtual float getLookAtEyeAngleMaxV() const;
    virtual float getTiltEyeBorderStart() const;
    virtual float getTiltEyeBorderEnd() const;
    virtual float getTiltEyeAngleScale() const;
    virtual float getCenterTiltRateMax() const;
    virtual float getNoseChildLocalOffset() const;
    virtual float getNoseStability() const;
    virtual float getNoseFriction() const;
    virtual float getNoseLimitDegree() const;
    virtual float getMustacheChildLocalOffset() const;
    virtual float getMustacheStability() const;
    virtual float getMustacheFriction() const;
    virtual float getMustacheLimitDegree() const;
    virtual int getCapInterpolateFrame() const;
    virtual float getCapChildLocalOffset() const;
    virtual float getCapStability() const;
    virtual float getCapFriction() const;
    virtual float getCapLimitDegree() const;
    virtual float getCapTransStability() const;
    virtual float getCapTransFriction() const;
    virtual float getCapTransLimit() const;
    virtual int getCapManHeroEyesWaitAppearFrame() const;
    virtual int getDeadWipeStartDamage() const;
    virtual int getDeadWipeWaitDamage() const;
    virtual int getDeadWipeStartAbyss() const;
    virtual int getDeadWipeWaitAbyss() const;
    virtual int getDeadWipeStartAbyssWithCapMsg() const;
    virtual int getDeadWipeWaitAbyssWithCapMsg() const;
    virtual int getDeadWipeStartPress() const;
    virtual int getDeadWipeWaitPress() const;
    virtual int getDeadWipeStartSandSink() const;
    virtual int getDeadWipeWaitSandSink() const;
    virtual int getDeadWipeStartNoOxygen() const;
    virtual int getDeadWipeWaitNoOxygen() const;
    virtual int getDeadWipeStartIceWater() const;
    virtual int getDeadWipeWaitIceWater() const;
    virtual float getCoinDashSpeed() const;
    virtual float getCoinDashSpeedLimit() const;
    virtual float getAdditionalSpeedLimit() const;

private:
    float mGravity;
    float mFrictionAttack;
    float mPushPower;
    float mWaitPoseDegreeMax;
    float mHillPoseDegreeMax;
    float mTiltPoseDegreeMax;
    float mSlerpQuatRate;
    float mSlerpQuatRateWait;
    float mSlerpQuatGrav;
    int mPreInputFrameCapThrow;
    int mEnableActionFrameCapCatch;
    float mJumpPowerCapCatch;
    float mJumpGravityCapCatch;
    int mRunTimeContinuousThrow;
    float mRunSpeedMaxContinuousThrow;
    int mRunAccelFrameContinuousThrow;
    float mSeparateCheckHeight;
    float mSeparateOffsetLerpRate;
    float mSeparateEnableThrowHeight;
    float mTall;
    float mCollisionRadius;
    float mCollisionRadiusSquat;
    float mCollisionRadiusStand;
    float mCollisionSmallStepHeight;
    float mCollisionResetLimit;
    float mReflectCeilingPower;
    float mReflectTossPower;
    float mReflectUpperPunchScaleH;
    float mCollisionHitDownAngleH;
    float mCollisionHitDownEscapeAngleV;
    float mShadowDropHeightScale;
    float mShadowDropNormalAdd;
    float mShadowDropLengthMin;
    float mShadowDropLengthMax;
    float mShadowDropLengthExtend;
    float mGravityDamage;
    float mHopPowerDamage;
    float mPushPowerDamage;
    int mDamageCancelFrame;
    int mDamageInvalidCount;
    int mDamageInvalidCountRecovery;
    int mDamageInvalidCountAbyss;
    float mNormalMinSpeed2D;
    float mNormalMaxSpeed2D;
    float mDashMaxSpeed2D;
    int mNormalAccelFrame2D;
    int mDashAccelFrame2D;
    int mNormalDashAnimFrame2D;
    int mNormalBrakeFrame2D;
    int mStickOnBrakeFrame2D;
    int mBrakeTurnStartFrame2D;
    float mTurnEndSpeedRate2D;
    float mJumpPowerMin2DArea;
    float mJumpPowerMax2DArea;
    float mJumpPowerMinBorder2D;
    float mJumpPowerMaxBorder2D;
    float mGravityMove;
    float mNormalMaxSpeed;
    float mNormalMinSpeed;
    int mNormalAccelFrame;
    float mRunAccelAverageScale;
    int mNormalBrakeFrame;
    float mDashJudgeSpeed;
    int mStickOnBrakeFrame;
    int mNormalDashAnimFrame;
    float mRunAfterTurnSpeedMax;
    float mRunAfterTurnScale;
    int mRunAfterTurnFrame;
    int mBrakeTurnStartFrame;
    float mBrakeOnSpeedRate;
    int mBrakeOnCounterBorder;
    int mWallPushFrame;
    int mRunDeepDownFrame;
    int mRunDeepDownMargine;
    int mQuickTurnJumpFrame;
    int mRoundAccelFrame;
    int mRoundBrakeFrame;
    float mRoundFastDegree;
    int mRoundAccelFrameFast;
    float mRoundMinDegree;
    int mRoundBrakeFrameForce;
    float mRoundFastDegreeForce;
    float mRoundLimitDegreeForce;
    float mRoundLimitDegreeForceFast;
    int mRoundAccelFrameForceFast;
    float mRoundLimitDegreeMin;
    float mRoundLimitDegree;
    int mIceAccelFrame;
    int mIceBrakeFrame;
    int mIceBrakeFrameHigh;
    int mIceBrakeFrameWall;
    int mIceRoundAccelFrame;
    int mIceRoundAccelFrameFast;
    int mIceRoundBrakeFrame;
    float mIceRoundFastDegree;
    float mIceRoundMinDegree;
    float mIceRoundLimitDegree;
    float mHillAddSpeed;
    float mHillSubSpeed;
    int mHillAccelAddFrame;
    int mHillAccelSubFrame;
    float mHillAccelSubAngleMin;
    float mHillAccelSubAngleMax;
    float mStandAngleMin;
    float mStandAngleMax;
    float mHillAngleSpeedMin;
    float mHillAngleSpeedMax;
    int mSpinCapThrowFrame;
    int mSpinCapThrowFrameAir;
    int mSpinCapThrowFrameSwim;
    int mSpinCapThrowFrameSwing;
    int mSpinCapThrowFrameContinuous;
    int mSpinAttackFrame;
    int mSpinBrakeFrame;
    float mSpinAirJumpPower;
    float mSpinAirSpeedMax;
    float mGravitySpinAir;
    float mSlerpQuatRateSpinAir;
    float mSpinBrakeRate;
    float mSpinBrakeSideAccel;
    float mSpinBrakeSideBrakeRate;
    float mSpinBrakeSideMaxSpeedRate;
    float mSpinRoundLimitDegree;
    float mDamageFireJumpPower1st;
    float mDamageFireJumpPower2nd;
    float mDamageFireJumpMoveSpeed;
    float mDamageFireCeilHitSpeed;
    float mDamageFireGravity;
    int mDamageFireNoGravityFrame;
    int mDamageFireRunTime;
    float mDamageFireRunSpeed;
    float mDamageFireRunBrakeFrame;
    int mSandSinkDeadTime;
    int mSandSinkBrakeHeightH;
    int mSandSinkBrakeHeightV;
    float mSandSinkHeight;
    float mSandSinkCapThrow;
    float mSandSinkBrakeMinH;
    float mSandSinkBrakeMaxH;
    float mSandSinkBrakeMinV;
    float mSandSinkBrakeMaxV;
    float mSlopeSlideAngleStart;
    float mSlopeSlideAngleEnd;
    float mSlopeSlideAccel;
    float mSlopeSlideBrake;
    float mSlopeSlideMaxSpeed;
    float mSlopeSlideSpeedEnd;
    float mSlopeSlideSideAccel;
    float mSlopeSlideSideBrake;
    float mSlopeSlideSideMaxSpeed;
    float mSlopeTurnDegree;
    int mSlideInvalidFrame;
    int mSlopeForceFrame;
    float mSlopeSlideForceSideAccel;
    float mSlopeSlideForceSideBrake;
    float mSlopeSlideForceSideMaxSpeed;
    float mSlopeSlideForceTurnDegree;
    float mSlopeRollingSpeedStart;
    float mSlopeRollingSpeedBoost;
    float mSlopeRollingMaxSpeed;
    int mSlopeRollingFrameMinBoost;
    int mSlopeRollingFrameMin;
    float mSlopeRollingStartJumpPower;
    float mSlopeRollingStartSlideSpeed;
    float mSlopeRollingAccel;
    float mSlopeRollingBrake;
    float mSlopeRollingAgainst;
    float mSlopeRollingAnglePowerMax;
    float mSlopeRollingSpeedEnd;
    float mSlopeRollingSideAccel;
    float mSlopeRollingSideBrake;
    float mSlopeRollingSideMaxSpeed;
    int mSlopeRollingUnRollFrame;
    float mSlopeRollingEndBrake;
    float mSlopeRollingEndBrakeEndSpeed;
    float mSlopeRollingReStartAccel;
    float mSlopeRollingReStartMaxAdd;
    int mSlopeRollingReStartinterval;
    int mSlopeRollingReStartSwing;
    int mSlopeRollingReStartCharge;
    int mSlopeRollingReStartForce;
    float mSlopeRollingAccelOnSkate;
    float mSlopeRollingSideAccelOnSkate;
    float mSlopeRollingBrakeOnSkate;
    int mExtendFrame;
    float mJumpInertiaRate;
    float mJumpPowerMin;
    float mJumpPowerMax;
    float mJumpGravity;
    float mJumpBaseSpeedMax;
    float mJumpMoveSpeedMin;
    float mJumpMoveSpeedMax;
    float mJumpAccelFront;
    float mJumpAccelBack;
    float mJumpAccelTurn;
    float mJumpTurnAngleStart;
    float mJumpTurnAngleLimit;
    float mJumpTurnAngleFast;
    float mJumpTurnAngleFastLimit;
    int mJumpTurnAccelFrame;
    int mJumpTurnAccelFrameFast;
    int mJumpTurnBrakeFrame;
    float mTrampleGravity;
    float mTrampleJumpPower;
    float mTrampleHighGravity;
    float mTrampleHighJumpPower;
    float mTrampleGravity2D;
    float mTrampleJumpPower2D;
    float mTrampleHighGravity2D;
    float mTrampleHighJumpPower2D;
    float mTrampleHipDropGravity;
    float mTrampleHipDropJumpPower;
    float mTrampleRisingBrakeVelH;
    float mTrampleJumpCodePower;
    float mTrampleJumpCodePowerSmall;
    float mCapLeapFrogJumpGravity;
    float mCapLeapFrogJumpPower;
    float mCapLeapFrogJumpPowerAir;
    float mObjLeapFrogJumpPower;
    float mObjLeapFrogJumpPowerHigh;
    float mCapHeadSpringJumpGravity;
    float mCapHeadSpringJumpPower;
    float mCapHeadSpringJumpGravityHigh;
    float mCapHeadSpringJumpPowerHigh;
    float mCapHeadSpringSpeedMax;
    int mContinuousJumpPreInputFrame;
    int mContinuousJumpCount;
    int mContinuousJumpTimer;
    float mContinuousJumpPowerMin;
    float mJumpPowerMax2nd;
    float mJumpGravity2nd;
    float mJumpPowerMax3rd;
    float mJumpGravity3rd;
    float mSpinFlowerJumpGravity;
    float mSpinFlowerJumpFallSpeedMax;
    float mSpinFlowerJumpMovePower;
    float mSpinFlowerJumpVelMax;
    int mSpinFlowerJumpStayFrame;
    float mSpinFlowerJumpStaySpeedMax;
    float mSpinFlowerJumpNoInputBrake;
    float mSpinFlowerJumpDownFallInitSpeed;
    float mSpinFlowerJumpDownFallPower;
    float mSpinFlowerJumpDownFallSpeedMax;
    float mJumpGravityForceRun;
    float mJumpPowerForceRun;
    float mCapCatchPopPower;
    float mCapCatchPopGravity;
    float mSquatJumpGravity;
    float mSquatJumpPower;
    float mSquatJumpBackPower;
    float mSquatJumpMovePowerFront;
    float mSquatJumpMovePowerSide;
    float mSquatJumpMoveSpeedMax;
    float mTurnJumpGravity;
    float mTurnJumpPower;
    float mTurnJumpVelH;
    float mTurnJumpBrake;
    float mTurnJumpAccel;
    float mTurnJumpSideAccel;
    float mLongJumpAccel;
    float mLongJumpBrake;
    float mLongJumpSideAccel;
    float mLongJumpGravity;
    float mLongJumpJumpPow;
    float mLongJumpMovePow;
    float mLongJumpInitSpeed;
    float mLongJumpSpeed;
    float mLongJumpSpeedMin;
    int mContinuousLongJumpCount;
    int mContinuousLongJumpTimer;
    float mGravityAir;
    float mFrictionAir;
    float mFallSpeedMax;
    float mLongFallDistance;
    float mFallWallScaleVelocity;
    int mDownFallFrameMin;
    float mGravityWallSlide;
    float mWallHeightLowLimit;
    float mWallKeepDegree;
    int mWallKeepFrame;
    float mWallJumpGravity;
    float mWallJumpHSpeed;
    float mWallJumpPower;
    int mWallJumpInvalidateInputFrame;
    int mWallInhibitAfterPunch;
    float mWallFollowAngleH;
    float mWallFollowAngleV;
    float mWallCatchDegree;
    float mWallCatchHeightEdgeTop;
    float mWallCatchHeightBottom;
    float mWallCatchKeepDegree;
    float mWallCatchMoveDegree;
    float mWallCatchMoveSpeed;
    float mWallCatchMoveHeightRange;
    int mWallCatchMoveinterpolate;
    int mWallCatchMoveFrame;
    int mWallCatchMoveFrameFast;
    int mWallCatchMoveFrameSwing;
    float mWallCatchInputRepeatAngle;
    float mWallClimbDegree;
    int mWallClimbJumpStartFrame;
    int mWallClimbJumpEndFrame;
    int mWallClimbStartFrame;
    float mWallClimbGravity;
    float mWallFallJumpSpeed;
    float mWallClimbJumpSpeedV;
    float mWallClimbJumpSpeedH;
    float mWallClimbJumpGravity;
    int mWallClimbJumpInvalidFrame;
    float mWallCatchHipLocalOffset;
    float mWallCatchHipStability;
    float mWallCatchHipFriction;
    float mWallCatchHipLimitDegree;
    float mWallCatchStainAreaOffset;
    float mGrabCeilRange;
    float mGrabCeilBodyRadius;
    float mGrabCeilLeaveSpeedMin;
    float mGrabCeilLeavePopPower;
    float mGrabCeilLeavePopGravity;
    float mGrabCeilSwingStartOffset;
    float mGrabCeilReverseInputBorder;
    float mGrabCeilInputPowerBorder;
    float mGrabCeilSwingWaitEnergy;
    float mGrabCeilEnableJumpEnergy;
    float mGrabCeilEnableJumpEnergyMax;
    float mGrabCeilJumpForceAngle;
    float mGrabCeilJumpPower;
    float mGrabCeilJumpMoveMin;
    float mGrabCeilJumpMoveMax;
    float mGrabCeilJumpGravity;
    int mGrabCeilJumpInvalidFrame;
    int mGrabCeilEnableNextFrame;
    int mGrabCeilEnableFallSnapFrame;
    int mPoleClimbPreInputSwing;
    float mPoleClimbInputRepeatAngle;
    float mPoleClimbInputDegreeMove;
    float mPoleClimbCatchRange;
    float mPoleClimbCatchRangeMin;
    float mPoleClimbCatchRangeMax;
    float mPoleClimbJointAngleMin;
    float mPoleClimbJointAngleMax;
    float mPoleClimbJointRangeMin;
    float mPoleClimbJointRangeMax;
    float mPoleClimbMoveWallDegree;
    float mPoleClimbUpMargine;
    float mPoleClimbUpSpeed;
    int mPoleClimbUpFrame;
    int mPoleClimbUpFrameFast;
    int mPoleClimbUpFrameSwing;
    float mPoleClimbDownSpeed;
    float mPoleClimbDownSpeedFast;
    float mPoleClimbDownSpeedSwing;
    int mPoleClimbDownFrame;
    int mPoleClimbDownKeepTime;
    float mPoleClimbTurnDist;
    int mPoleClimbTurnFrame;
    int mPoleClimbTurnStopFrame;
    int mPoleTopStartFrame;
    int mPoleTopEndFrame;
    float mPoleTopTurnSpeed;
    float mPoleTopEndUnderOffsetY;
    int mGroundSpinFrame;
    float mGroundSpinMoveSpeedMax;
    float mGroundSpinAccelRate;
    float mGroundSpinBrakeRate;
    float mSpinJumpGravity;
    float mSpinJumpPower;
    float mSpinJumpMoveSpeedMax;
    float mSpinJumpDownFallInitSpeed;
    float mSpinJumpDownFallPower;
    float mSpinJumpDownFallSpeedMax;
    float mSquatBrakeEndSpeed;
    float mSquatAccelRate;
    float mSquatBrakeRate;
    float mSquatBrakeRateOnSkate;
    float mSquatBrakeSideAccel;
    float mSquatBrakeSideRate;
    float mSquatBrakeSideAccelOnSkate;
    float mSquatBrakeSideRateOnSkate;
    float mSquatBrakeSideMaxSpeedRate;
    float mSquatWalkSpeed;
    float mSquatWalkTurnSpeed;
    int mSquatWalkTurnFrame;
    float mSquatJumpCeilSlideSpeed2D;
    float mHipDropSpeed;
    float mHipDropGravity;
    float mHipDropSpeedMax;
    int mHipDropLandCancelFrame;
    float mHipDropHeight;
    int mHipDropMsginterval;
    float mJumpHipDropPower;
    int mJumpHipDropPermitBeginFrame;
    int mJumpHipDropPermitEndFrame;
    float mHeadSlidingSpeed;
    float mHeadSlidingSpeedMin;
    float mHeadSlidingBrake;
    float mHeadSlidingSideAccel;
    float mHeadSlidingJump;
    float mHeadSlidingGravityAir;
    float mSwimCenterOffset;
    float mSwimWallCatchOffset;
    float mSwimRisePower;
    float mSwimRiseSpeedMax;
    int mSwimRiseFrame;
    float mSwimGravity;
    float mSwimGravityWalk;
    float mSwimFallSpeedMax;
    float mSwimFloorAccelH;
    float mSwimFloorSpeedMaxH;
    float mSwimHighAccelH;
    float mSwimHighSpeedMaxH;
    float mSwimLowAccelH;
    float mSwimLowSpeedMaxH;
    float mSwimBrakeRateH;
    float mSwimWallHitSpeedMinH;
    int mSwimHighAccelPermitFrame;
    float mSwimFlowFieldBlend;
    float mSwimWalkAnimMinRate;
    float mSwimWalkAnimMaxRate;
    float mSwimWalkMaxSpeed;
    float mSwimSpinCapUpPower;
    float mSwimSpinCapUpSpeedMax;
    float mSwimRotStartAngle;
    float mSwimRotFastAngle;
    int mSwimRotAccelFrame;
    int mSwimRotAccelFrameFast;
    int mSwimRotBrakeFrame;
    float mSwimRotSpeedChangeStart;
    float mSwimRotSpeedForward;
    float mSwimRotSpeedMax;
    float mSwimSurfaceAccelH;
    float mSwimSurfaceSpeedMaxH;
    int mSwimSurfaceSpinCapFrame;
    float mSwimSurfaceSpinCapSpeedMaxH;
    float mSwimSurfaceStartDist;
    float mSwimSurfaceEndDist;
    float mSwimSurfaceGravity;
    float mSwimSurfaceBaseHeight;
    float mSwimSurfaceSpring;
    float mSwimSurfaceDamper;
    int mSwimSurfaceDamperStart;
    int mSwimSurfaceDamperFrame;
    float mSwimSurfaceEnableJumpHeight;
    int mSwimSurfacePreInputJumpFrame;
    float mSwimSurfaceMoveSpring;
    float mSwimSurfaceMoveDamper;
    float mSwimSurfaceMoveBaseHeight;
    float mSwimRunSurfaceBaseHeight;
    float mSwimRunSurfaceApproachRate;
    float mSwimRunSurfaceApproachLimit;
    float mSwimRunSurfaceBrakeBorder;
    float mSwimRunSurfaceBrakeH;
    float mSwimRunSurfaceApproachBorderMax;
    float mSwimRunSurfaceApproachBorderMin;
    float mSwimRunSurfaceApproachRateMin;
    float mSwimFallInSpeed;
    float mSwimFallInBrakeH;
    float mSwimFallInBrakeV;
    float mSwimHeadInBrakeH;
    float mSwimHeadInBrakeV;
    float mSwimHeadInRisePower;
    float mSwimHeadInRiseSpeedMax;
    float mSwimHeadInSurfaceHeight;
    int mSwimFallInForceSurfaceFrame;
    int mSwimFallInvalidJumpFrame;
    float mSwimDiveStartSpeed;
    float mSwimDiveBrake;
    float mSwimDiveEndSpeed;
    int mSwimDiveLandCount;
    int mSwimDiveLandCancelFrame;
    int mSwimDiveNoBrakeFrame;
    int mSwimDiveButtonValidFrame;
    int mSwimDiveEndFrame;
    float mSwimDiveInBrakeH;
    float mSwimDiveInBrakeV;
    float mSwimDiveInRisePower;
    float mSwimDiveInRiseSpeedMax;
    float mSwimDiveInSurfaceHeight;
    int mSwimDiveInKeepFrame;
    int mSwimHeadSlidingFrame;
    int mSwimHeadSlidingBrakeFrame;
    float mSwimHeadSlidingSpeed;
    float mSwimHeadSlidingSpeedEnd;
    float mSwimHeadSlidingBrake;
    float mSwimHeadSlidingSideAccel;
    float mSwimHeadSlidingJump;
    float mSwimHeadSlidingGravity;
    int mSwimHeadSlidingEndBrakeFrame;
    int mSwimHeadSlidingEndSpeedMin;
    float mSwimJumpHipDropSpeed;
    float mSwimJumpHipDropBrakeV;
    float mSwimJumpHipDropBrakeVCeiling;
    float mSwimJumpHipDropGravity;
    float mSwimJumpHipDropCancelSpeed;
    float mSwimJumpHipDropAccelH;
    float mSwimJumpHipDropMoveSpeedH;
    float mSwimJumpHipDropPopSpeed;
    float mSwimJumpHipDropPopJumpAdd;
    float mSwimTramplePower;
    float mDiveTramplePower;
    int mDiveTrampleCancelFrame;
    float mDamageSwimPushPower;
    float mDamageSwimGravity;
    int mDamageSwimCancelFrame;
    float mDamageSwimSurfaceGravity;
    float mDamageSwimSurfaceHopPower;
    float mDamageSwimSurfacePushPower;
    float mDamageSwimSurfaceLandSpeed;
    float mDamageSwimSurfaceLandBrake;
    float mDamageSwimSurfaceLandEndSpeed;
    int mDamageSwimSurfaceCancelFrame;
    float mDamageSwimBrakeRateGround;
    int mOxygenReduceFrame;
    int mOxygenNoReduceFrame;
    int mOxygenRecoveryFrame;
    int mOxygenDamageinterval;
    int mIceWaterDamageinterval;
    int mIceWaterRecoveryFrame;
    float mMoveAnimSpeedMax;
    float mAnimFrameRateSpeedMin;
    float mRunBorderSpeed;
    float mRunBlendRange;
    float mDashBorderSpeed;
    float mDashBlendRange;
    float mDashFastBorderSpeed;
    float mDashFastBlendRange;
    float mAnimFrameRateSpeedMax;
    float mAnimFrameRateRunStart;
    float mAnimFrameRateMinRun;
    float mAnimFrameRateMaxRun;
    float mAnimFrameRateMaxDash;
    float mAnimFrameRateMaxDashFast;
    float mRunStartPlayFrameScale;
    int mRunStartBlendFrame;
    float mDamageFireRunAnimRate;
    float mRunSkateAnimSpeedOffset;
    float mAnimFrameRateRange2D;
    float mAnimFrameRateMinRun2D;
    float mAnimFrameRateMaxRun2D;
    int mIKBlendFrameRun;
    float mIKBlendRateRunMin;
    float mIKBlendRateRunMax;
    float mRollingAnimBorderSpeedMin;
    float mRollingAnimBorderSpeedMax;
    float mRollingAnimFrameRateMin;
    float mRollingAnimFrameRateMax;
    int mSwimPaddleAniminterval;
    int mSwimPaddleAnimRateintervalMax;
    int mSwimPaddleAnimRateintervalMin;
    float mSwimPaddleAnimMaxRate;
    float mSwimBentForwardMax;
    float mSwimBentForwardBlendRate;
    float mSwimBentSideMax;
    float mSwimBentSpineMax;
    float mSwimBentSideBlendRate;
    float mSwimBentFrontMax;
    float mSwimBentFrontBlendRate;
    float mSwimWalkAnimSpeedMax;
    float mSwimWalkAnimSpeedMin;
    float mSwimWalkAnimFrameRateMax;
    float mSwimWalkAnimFrameRateMin;
    float mSandSinkBorderMin;
    float mSandSinkBorderMax;
    float mSandSinkBorderRateMin;
    float mSandSinkBorderRateMax;
    float mSandSinkFrameRateMin;
    float mSandSinkFrameRateMax;
    int mLookAtEyeKeepFrame;
    int mLookAtEyeKeepFrameInSight;
    int mLookAtEyeKeepFrameWait;
    float mLookAtEyeDistance;
    float mLookAtEyeAngleMinH;
    float mLookAtEyeAngleMinInSightH;
    float mLookAtEyeAngleMaxH;
    float mLookAtEyeAngleMinV;
    float mLookAtEyeAngleMinInSightV;
    float mLookAtEyeAngleMaxV;
    float mTiltEyeBorderStart;
    float mTiltEyeBorderEnd;
    float mTiltEyeAngleScale;
    float mCenterTiltRateMax;
    float mNoseChildLocalOffset;
    float mNoseStability;
    float mNoseFriction;
    float mNoseLimitDegree;
    float mMustacheChildLocalOffset;
    float mMustacheStability;
    float mMustacheFriction;
    float mMustacheLimitDegree;
    int mCapinterpolateFrame;
    float mCapChildLocalOffset;
    float mCapStability;
    float mCapFriction;
    float mCapLimitDegree;
    float mCapTransStability;
    float mCapTransFriction;
    float mCapTransLimit;
    int mCapManHeroEyesWaitAppearFrame;
    int mDeadWipeStartDamage;
    int mDeadWipeWaitDamage;
    int mDeadWipeStartAbyss;
    int mDeadWipeWaitAbyss;
    int mDeadWipeStartAbyssWithCapMsg;
    int mDeadWipeWaitAbyssWithCapMsg;
    int mDeadWipeStartPress;
    int mDeadWipeWaitPress;
    int mDeadWipeStartSandSink;
    int mDeadWipeWaitSandSink;
    int mDeadWipeStartNoOxygen;
    int mDeadWipeWaitNoOxygen;
    int mDeadWipeStartIceWater;
    int mDeadWipeWaitIceWater;
    float mCoinDashSpeed;
    float mCoinDashSpeedLimit;
    float mAdditionalSpeedLimit;
};
