name: testcompile
on: [push, pull_request]
permissions: {}

jobs:
  test_compile:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out project
      uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Set up dependencies
      run: |
        sudo apt update && sudo apt install -y ninja-build cmake ccache clang curl
    - name: Set up python
      uses: actions/setup-python@v7
      with:
        python-version: '3.14'
        cache: 'pip'
    - name: Set up python package dependencies
      run: pip install toml
    - name: Set up cache for toolchain
      uses: actions/cache@v6
      with:
        key: tools_libs
        path: |
          toolchain/bin
          toolchain/libcxx-include
          toolchain/cache-version-url.txt
    - name: Run simplified setup
      run: tools/setup.py --project
    - name: Create testing source files
      run: bash ./.github/scripts/test-compile-create.sh
    - name: Build project
      run: tools/build.py
